### PR TITLE
Method overhaul with static PyMethodDef

### PR DESCRIPTION
**Pull request by youknowone**
I found #4686 is related to multiple design caveats. I originally tried to edit small enough to support the original PR, but found this way will reduce total cost of effort about them.

closes #4686 by including all its changes.

### CODE REVIEW

**Comment by youknowone** [comment]
Split PRs to: #4886 #4898 #4899 #4900 #4901

**Comment by youknowone** [comment]
@moreal  This is not fully done, but could you give it a look? This is also related to `PyMember` design, so maybe you will be interested in.

**Comment by youknowone** [comment]
Finally all tests pass

**Comment by youknowone** [comment]
@seungha-kim @moreal Could you review this PR?

**Review by moreal — APPROVED** [review]
I had tried to review it well but I'm not sure I've done a good job of reviewing long pieces of code. But I had read it once, and it builds and tests well, so I approve.

**Pull request merged**
