### PR TITLE
Py module macro

### PR DESCRIPTION
**Pull request by cthulahoops**

### CODE REVIEW

**Comment by coolreader18** [comment]
I did something similar in #247, this looks a bit less "magic" (which is a good thing).

**Comment by cthulahoops** [comment]
I quite liked the very magic version. :)

I hope the simpler version is a reasonable compromise.

**Comment by cthulahoops** [comment]
These coverage reports are interested. I've decreased coverage despite not adding any new code.

**Comment by OddCoincidence** [comment]
Yeah, I think it counts macro bodies and comments against you. :disappointed:

**Comment by windelbouwman** [comment]
As the main person against too much macros, I approve of this macro!

**Pull request merged**
