### PR TITLE
Add unittest module python files.

### PR DESCRIPTION
**Pull request by windelbouwman**
The module does not function correctly yet, but I figured we could check it in already.

### CODE REVIEW

**Comment by coolreader18** [comment]
Ah, I was just about to make a PR that included fnmatch and contextlib, with the async parts of contextlib removed so it didn't panic. Do you want to rebase onto that?

**Comment by coolreader18** [comment]
#1136

**Comment by palaviv** [comment]
Is `import unittest` working? The last time I tried we were missing a few libraries.

**Comment by windelbouwman** [comment]
We still lack the argparse library. Thats where it is stuck now. Also, sys.stdout is missing.

**Comment by palaviv** [comment]
I would prefer not adding code that we can't import yet.

**Comment by coolreader18** [comment]
And `argparse` -> `gettext` -> `locale` -> `_locale`, so we're going to need to implement `_locale` next.

**Comment by coolreader18** [comment]
I had the same sort of thought process as palaviv, as in all the stdlib code we commit should be working or at least be able to be imported, but I'm open to discussion.

**Comment by windelbouwman** [comment]
I agree that the code should import without error. I'll close this pull request.

**Pull request closed without merging**
