### PR TITLE
Builtin ord improvements

### PR DESCRIPTION
**Pull request by Jongy**

### CODE REVIEW

**Comment by youknowone** [comment]
The unit tests for `ord()` is in `tests/snippets/builtin_ord.py`

**Comment by Jongy** [comment]
> The test snippets for ord() are in tests/snippets/builtin_ord.py

The "0 characters" case is already tested, however the exception message itself is not tested (And that's what I fixed, to match CPython's behavior).
The question is, do we want to test such exact behavior regarding raised exceptions?

**Comment by youknowone** [comment]
I thought the error message is changed and so now wrong messages are written in the code.
But it seems the messages are not tested as you said. I am sorry to bothering you.

I don't know much about the test policy. Maybe other people will explain about it.

**Comment by windelbouwman** [comment]
There is no test policy set in stone. We have some snippets, hitting most of the code paths, but testing is not very strict.

**Pull request merged**
