### PR TITLE
Moved get_attribute and del_attr to use call_or_unsupported. Adresses #198

### PR DESCRIPTION
**Pull request by haneybarg**
I changed both `get_attribute` and `del_attr` to use the `call_or_unsupported` method. I did not change `to_str` and ` to_repr` though, as this would require a refactoring of the call_or_unsupported to allow only one PyObject.

### CODE REVIEW

**Comment by windelbouwman** [comment]
Hello @haneybarg thank you for your contribution to this project. Are you sure python supports `__rgetattribute__`? Not all methods have a reversed operation. Please check cpython as a reference for this.

**Comment by haneybarg** [comment]
It does not appear to be supported. How should I proceed?

**Comment by windelbouwman** [comment]
Please open another pull request and look for something else to implement. One way to find something missing is simply try `cargo run` and try python commands and see what you miss.

**Comment by windelbouwman** [comment]
I'll close this pull request, since python does not have rdelattr methods.

**Pull request closed without merging**
