### PR TITLE
Declare ourselves as Python 3.9

### PR DESCRIPTION
**Pull request by coolreader18**
Python 3.5 is pretty old at this point, and I think we generally try to keep up with the latest features (e.g. assignment expression, self-documenting fstrings), so I think it makes sense to say we're 3.9. I put 3.8 in the READMEs because I don't think we have full 3.9 compatibility yet and 3.8 is more used, but I'm not really sure if that makes a difference :shrug:

### CODE REVIEW

**Review by youknowone — APPROVED** [review]

**Comment by domdfcoding** [comment]
What was the rationale for changing the site-packages paths to rustpythonX.Y? pip seems to be hardcoded to install to pythonX.Y and PyPy uses pythonX.Y too.

**Comment by coolreader18** [comment]
It seems like pip respects the rustpythonX.Y path in my experience, and I think my motivation was that we don't have anywhere close to full compatibility for many libraries (especially that require native C extensions) so I feel it makes sense to keep them separate, at least for now.

**Comment by domdfcoding** [comment]
Makes sense. 

I think the pip behaviour I saw is because there's still a reference to the `pythonX.Y` form in `distutils.sysconfig`:

https://github.com/RustPython/RustPython/blob/2bcf7d4d5b0d16b5e0f0dab555ba222f42aaf796/Lib/distutils/sysconfig.py#L136-L138

and in `distutils.command.install`: 

https://github.com/RustPython/RustPython/blob/2bcf7d4d5b0d16b5e0f0dab555ba222f42aaf796/Lib/distutils/command/install.py#L30-L37

If I change those by hand pip installs to the correct location.

**Comment by coolreader18** [comment]
Huh, interesting, it installs to the right place on my machine but feel free to make a PR if that fixes it in your environment.

**Pull request merged**
