### PR TITLE
Revert "Make CodeObject.source_path an Option<String>", just add a parameter to import_codeobj

### PR DESCRIPTION
**Pull request by coolreader18**
Reverts RustPython/RustPython#1037. See https://github.com/RustPython/RustPython/pull/1037#issuecomment-504101074

### CODE REVIEW

**Comment by coolreader18** [comment]
Wait nevermind, I have a better idea of how to implement this.

**Comment by coolreader18** [comment]
Nevermind that actually

**Comment by coolreader18** [comment]
@palaviv I decided to go with just a parameter to `import_codeobj` because `CodeObject`s come from a lot of different sources than just script files or frozen modules (e.g. functions) and in those contexts it doesn't make sense to put the metadata in the `CodeObject` itself.

**Comment by palaviv** [comment]
Look great :+1:

**Pull request merged**
