### PR TITLE
Copy gzip from CPython 3.10

### PR DESCRIPTION
**Pull request by verhovsky**

### CODE REVIEW

**Comment by verhovsky** [comment]
I tried copying over `test_gzip` as well, but I get this `Expected at most 1 arguments (4 given)` error a lot:

```
======================================================================
ERROR: test_bad_gzip_file (__main__.TestGzip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Lib/test/test_gzip.py", line 421, in test_bad_gzip_file
    self.assertRaises(gzip.BadGzipFile, file.readlines)
  File "Lib/test/test_gzip.py", line 421, in test_bad_gzip_file
    self.assertRaises(gzip.BadGzipFile, file.readlines)
  File "/home/boris/code/RustPython/vm/pylib-crate/Lib/unittest/case.py", line 746, in assertRaises
    context = None
  File "/home/boris/code/RustPython/vm/pylib-crate/Lib/unittest/case.py", line 743, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/home/boris/code/RustPython/vm/pylib-crate/Lib/unittest/case.py", line 743, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/home/boris/code/RustPython/vm/pylib-crate/Lib/unittest/case.py", line 181, in handle
    self = None
  File "/home/boris/code/RustPython/vm/pylib-crate/Lib/unittest/case.py", line 178, in handle
    callable_obj(*args, **kwargs)
  File "/home/boris/code/RustPython/vm/pylib-crate/Lib/unittest/case.py", line 178, in handle
    callable_obj(*args, **kwargs)
  File "/home/boris/code/RustPython/vm/pylib-crate/Lib/gzip.py", line 398, in readline
    return self._buffer.readline(size)
  File "/home/boris/code/RustPython/vm/pylib-crate/Lib/_compression.py", line 69, in readinto
    byte_view[:len(data)] = data
TypeError: Expected at most 1 arguments (4 given)
```

It seems like it might be because the `memoryview` is opened in a `with` statement, and there's some cleanup it's failing to do. To get the same error not in tests, you can run this file:

```py
import gzip

data1 = b"""  int length=DEFAULTALLOC, err = Z_OK;
  PyObject *RetVal;
  int flushmode = Z_FINISH;
  unsigned long start_total_out;

"""

filename = '/tmp/file.txt'

with open(filename, 'wb') as f:
    f.write(data1 * 50)
with gzip.GzipFile(filename, 'r') as f:
    f.readlines()
```

Which will give you this error:

```
$ RUSTPYTHONPATH=Lib cargo run --release bad_gzip_file.py 
    Finished release [optimized] target(s) in 0.09s
     Running `target/release/rustpython bad_gzip_file.py`
Traceback (most recent call last):
  File "/home/boris/code/RustPython/vm/pylib-crate/Lib/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/boris/code/RustPython/vm/pylib-crate/Lib/gzip.py", line 487, in read
    if not self._read_gzip_header():
  File "/home/boris/code/RustPython/vm/pylib-crate/Lib/gzip.py", line 435, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
BadGzipFile: Not a gzipped file (b'  ')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/boris/code/RustPython/vm/pylib-crate/Lib/_compression.py", line 69, in readinto
    byte_view[:len(data)] = data
TypeError: Expected at most 1 arguments (4 given)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bad_gzip_file.py", line 17, in <module>
    f.readlines()
  File "bad_gzip_file.py", line 17, in <module>
    f.readlines()
  File "/home/boris/code/RustPython/vm/pylib-crate/Lib/gzip.py", line 398, in readline
    return self._buffer.readline(size)
  File "/home/boris/code/RustPython/vm/pylib-crate/Lib/_compression.py", line 69, in readinto
    byte_view[:len(data)] = data
TypeError: Expected at most 1 arguments (4 given)
```

**Comment by coolreader18** [comment]
I think it's just the `with` error that was causing the problem, I've pushed a commit that should fix it if you want to try adding test_gzip again.

**Comment by coolreader18** [comment]
Yeah, looking at it now, there's only a few errors left in test_gzip.

**Comment by verhovsky** [comment]
@coolreader18 did I understand the reason those 3 tests fail correctly? This file:

```py
import gzip
import os

data1 = b"""  int length=DEFAULTALLOC, err = Z_OK;
  PyObject *RetVal;
  int flushmode = Z_FINISH;
  unsigned long start_total_out;

"""

filename = "/tmp/file.txt"


def write_and_read_back(data, mode="b"):
    b_data = bytes(data)
    with gzip.GzipFile(filename, "w" + mode) as f:
        l = f.write(data)
    assert l == len(b_data)
    with gzip.GzipFile(filename, "r" + mode) as f:
        assert f.read() == b_data

with gzip.open(filename, "wb") as f:
    f.write(b"foo\xffbar")
with gzip.open(filename, "rt", encoding="ascii", errors="ignore") as f:
    assert f.read() == "foobar"
```

produces this error:

```
Traceback (most recent call last):
  File "test_gzip.py", line 41, in <module>
    assert f.read() == "foobar"
  File "test_gzip.py", line 41, in <module>
    assert f.read() == "foobar"
UnicodeDecodeError: cannot decode byte at index: 3
```

**Comment by coolreader18** [comment]
@verhovsky yeah, that's right, we just use `str::from_utf8` instead of going through the machinery of the `encodings` module.

**Review by coolreader18 — APPROVED** [review]

**Comment by coolreader18** [comment]
Thanks for contributing!

**Pull request merged**
