### PR TITLE
os: implement fork

### PR DESCRIPTION
**Pull request by yossi-k**
This seems to work and tests pass (`test_posix:test_register_at_fork`).

I took a look at CPython's implementation and it seems they're doing more things before/after fork, namely acquiring the import lock, and re-initiating the interpreter in the child process (see here - https://github.com/python/cpython/blob/main/Modules/posixmodule.c#L593). Do we want to do the same thing here?

### CODE REVIEW

**Review by youknowone — APPROVED** [review]
I personally support hard compatibility with CPython.
At least, leaving comments about CPython implementations for each places will be helpful for future workers.

**Comment by youknowone** [comment]
what's happend to the ubuntu tests?

**Comment by yossi-k** [comment]
I’ll take another look. The problem is that fork enables functions like os.spawn which in turn enable a whole bunch of new tests.

**Comment by DimitrisJim** [comment]
thanks! This is superseded by https://github.com/RustPython/RustPython/pull/4877 if I'm not mistaken. Feel free to re-open if I'm mistaken.

**Pull request closed without merging**
