### PR TITLE
Add format %e option of floating point numbers.

### PR DESCRIPTION
**Pull request by ChJR**

### CODE REVIEW

**Review by youknowone — COMMENTED** [review]
The change generally looks good. 
will you please add a test for this?
Also please check the clippy errors

**Comment by ChJR** [comment]
I see. I added some tests and fixed clippy error.

**Comment by coolreader18** [comment]
Actually, we don't usually add our own tests to `Lib/test`, since that's a CPython library file that we might update at times like you did `random.py`. Could you move the test to somewhere in `extra_tests/snippets`? `strings.py` looks like it fits.

**Comment by ChJR** [comment]
That's what I want to know. I'll move the test to extra_tests. Thanks for reviewing my code.

**Review by coolreader18 — APPROVED** [review]

**Comment by coolreader18** [comment]
Thanks for contributing!

**Pull request merged**
