### PR TITLE
Refactor list avoid duplicate the vec

### PR DESCRIPTION
**Pull request by qingshi163**
This is like another appaorch to replace #2933 

This will avoid duplicate the vec before the loop.

This will have compatible result when changing the list while looping.

This may have more overhead as we lock and unlock the list for each comparison operation.

Possible optimization:
- keeping the lock for internal classes if we can identify it.

Please advise if this appoarch is acceptable or do we have better idea?
@youknowone

### CODE REVIEW

**Comment by youknowone** [comment]
When @DimitrisJim benchmarked similar stuff, the result showed collecting to vec is a lot cheaper than `n` lock-unlock

**Comment by DimitrisJim** [comment]
Slightly better for bigger lists but slightly worse for smaller ones, which makes sense considering a copy of the vector is made and size plays a big role in how fast that can be done.

**Comment by qingshi163** [comment]
If we could efficiently check does python class customize the eq slot, we could optimize to keep the lock.

**Comment by qingshi163** [comment]
Whatever the case we need to check the slot to call. So if we can identify the function in the slot is rust code, we could avoid one lock unlock, one rc clone for the object for each loop.

**Comment by youknowone** [comment]
do we need `member_descriptor`?

**Comment by DimitrisJim** [comment]
Microbenchmarking shows this executing slightly faster for builtins. With a custom type the old code is faster, checking for a custom `__eq__` would probably help with that.

Overall, this looks ok to me, it seems like it could also generalize for other collections like `deque`s and `array`s.

**Comment by youknowone** [comment]
the benchmark result sounds like we need to change the compare code but not about the locking

**Comment by qingshi163** [comment]
> the benchmark result sounds like we need to change the compare code but not about the locking

optimize the compare code make a big improvment.

on the other hand, the original clone the vec or this pr both have acceptable performence. this one is a little better for builtins but a little worse for custom types.

also as we are checking via list.count that have to go throw the whole list, the other function like list.remove, list.contains will in average return earlier. this appoarch should be slightly better than clone the whole vec.

or maybe we just ignore the compatibility, let who write the code like that just go to the hell :thinking:

**Comment by youknowone** [comment]
ah, got it. I didn't notice `count()` compatibility

**Pull request merged**
