### PR TITLE
Fix unwrap issue causing panic

### LINKED ISSUE #4312: Checking unmatched "raiseregex" leads to rustpython panicked
In the following example, we instance a object of unittest, then the unmatched error is collected by the assertRaisesRegex, rustpython get panicked.

test.py:

```
import unittest

class uTest(unittest.TestCase):
	pass

uTest = uTest()

with uTest.assertRaisesRegex(Exception, 'aaa'):
     aab
```

Behavior on rustpython(rustpython 0.1.2):
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', vm/src/suggestion.rs:55:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Expected behavior(behavior on CPython 3.9.1):
`NameError: name 'aab' is not defined`

Step to reproduce:
type "cargo run --release test.py" on the console of Ubuntu 18.04 and MacOS Big Sur 11.7.1
rust version: rustc 1.65.0

### PR DESCRIPTION
**Pull request by rileysu**
This fixes #4312.

### CODE REVIEW

**Comment by youknowone** [comment]
@Snowapril could you review this change?

**Review by Snowapril — APPROVED** [review]
LGTM! I cannot remember why did I use `unwrap` there haha..

**Review by DimitrisJim — CHANGES_REQUESTED** [review]
Great! This also appears to fix two tests (`test_issue45826` and `test_issue45826_focused`) in `test_exception.py`, un-comment both of them (and remove the `TODO: RUSTPYTHON` comment preceeding them in order for them to now run.

**Review by DimitrisJim — APPROVED** [review]
great, thanks!

**Pull request merged**
