### PR TITLE
Fixed several clippy warnings

### PR DESCRIPTION
**Pull request by ZapAnton**
Contributes to #291

Every commit in this PR fixed a single class of clippy warnings, with the link to the warning in the commit message.

Hopefully this will reduce the warning noise and will help to write more idiomatic code

### CODE REVIEW

**Comment by ZapAnton** [comment]
Fixed the merge conflict and the Travis failed checks. This PR is now ready for the review

**Comment by windelbouwman** [comment]
Thank you for this work! In order for this to work, I suggest to split this in several smaller pull requests. The work is now conflicted.

**Comment by windelbouwman** [comment]
@ZapAnton Shall we close this PR?

**Comment by ZapAnton** [comment]
Sure. Only #343 is left, so there is no need for this PR.

**Pull request closed without merging**
