### PR TITLE
Update parser

### PR DESCRIPTION
**Pull request by youknowone**

### CODE REVIEW

**Comment by DimitrisJim** [comment]
snippets failing is unrelated

**Comment by youknowone** [comment]
what's happening here?

**Comment by DimitrisJim** [comment]
this is a cpython failure, not rustpython one. I haven't had time to look into it yet.

**Comment by DimitrisJim** [comment]
yup, this is a change performed sometime between 3.11.3-3.11.4. Can't find anything in changelogs but locally with Python 3.11.2 it passes, should be just an error change in eval

**Pull request merged**
