### PR TITLE
Fix array with float

### PR DESCRIPTION
**Pull request by qingshi163**

### CODE REVIEW

**Review by coolreader18 — APPROVED** [review]

**Comment by coolreader18** [comment]
Any idea why windows snippets tests are failing?

**Comment by qingshi163** [comment]
incompatible issue from CPython?

**Comment by coolreader18** [comment]
Ah, probably, github might have updated the default CPython version

**Comment by coolreader18** [comment]
@qingshi163 try rebasing onto master, that should fix that CI issue

**Pull request merged**
