### PR TITLE
Fix test_bool test_subclass

### PR DESCRIPTION
**Pull request by minhrongcon2000**
Fix unsafe `__new__` for int function

### CODE REVIEW

**Review by youknowone — COMMENTED** [review]
Thank you for contributing, but this fix doesn't seem to correct implementation.

Could you check corresponding cpython implementation?
https://github.com/python/cpython/blob/main/Objects/typeobject.c#L7694-L7701

**Comment by minhrongcon2000** [comment]
Sure! I will check it when I have time :D

**Comment by minhrongcon2000** [comment]
@youknowone The block of code that you show me in the previous comment is to check whether `cls` is a subtype of the current class that called `__new__`. In CPython, however, `bool` is a subtype of int and in CPython, int is not allowed to call `__new__` with subtype as well. See https://github.com/python/cpython/blob/87be8d95228ee95de9045cf2952311d20dc5de45/Objects/typeobject.c#L7711-L7718

**Comment by youknowone** [comment]
Oh, i am sorry. I left wrong link

**Comment by Snowapril** [comment]
Oh .... It seems duplicate PR exist here #4455 😭 (cc. @youknowone )

**Comment by DimitrisJim** [comment]
yeah and that PR goes about things in the approach CPython has by modifying `type.__new__` to catch this.

**Comment by minhrongcon2000** [comment]
Oh! So I will close this PR now :D

**Comment by DimitrisJim** [comment]
we should just coordinate with garychia and see if they still want to work on it, I'll leave a comment there to check. If they don't have time, you can take inspiration from their approach :smile:

**Pull request closed without merging**
