### PR TITLE
Fix ensurepip install issues

### LINKED ISSUE #4589: pip is broken again on macOS
```
$ cargo run --release --features=ssl -- -m ensurepip
 Defaulting to user installation because normal site-packages is not writeable
Looking in links: /var/folders/4l/db5by6f97gl8z692_wckqb3w0000gn/T/tmpsqf2lk1o
Processing /private/var/folders/4l/db5by6f97gl8z692_wckqb3w0000gn/T/tmpsqf2lk1o/setuptools-65.5.0-py3-none-any.whl
Processing /private/var/folders/4l/db5by6f97gl8z692_wckqb3w0000gn/T/tmpsqf2lk1o/pip-22.3.1-py3-none-any.whl
Installing collected packages: setuptools, pip
Successfully installed pip-22.0.4 setuptools-67.4.0
$ cargo run --release --features=ssl -- -m pip
    Finished release [optimized] target(s) in 0.38s
     Running `target/release/rustpython -m pip`
./target/release/rustpython: No module named pip
```

### PR DESCRIPTION
**Pull request by DimitrisJim**
Closes #4589 (which most likely applied for all OS's). At some point it seems this change was removed from sysconfig by accident, this adds it back and also adds a check to the CI to make sure its caught in the future.

edit: Removed in #4569 which I also approved :smile:

### CODE REVIEW

**Comment by DimitrisJim** [comment]
p.s we should probably remove `--install-pip` now, no?

**Comment by youknowone** [comment]
Thanks, regression from a6e44a349a5c30fcee777e70601a05e5c5116f4c

**Comment by youknowone** [comment]
`--install-pip` also tries get-pip by parameter. idk if we will need it or not.

**Review by youknowone — APPROVED** [review]

**Comment by DimitrisJim** [comment]
I really don't know if there's a need for it either. Currently it also pulls down the newest version of pip which we can't run due to some `io` stuff missing if I remember correctly.

**Pull request merged**
