### PR TITLE
Fix the location of `BinOp`

### PR DESCRIPTION
**Pull request by harupy**
Fixes the location of `BinOp`.

### CODE REVIEW

**Comment by fanninpm** [comment]
To clarify…

Instead of:
```text
a | b
  ^
```

You want this?
```text
a | b
^
```

**Comment by harupy** [comment]
@fanninpm yes!

**Comment by harupy** [comment]
@fanninpm 

```python
>>> import ast
>>> print(ast.dump(ast.parse("1 + 2"), include_attributes=True, indent=2))
Module(
  body=[
    Expr(
      value=BinOp(
        left=Constant(
          value=1,
          lineno=1,
          col_offset=0,
          end_lineno=1,
          end_col_offset=1),
        op=Add(),
        right=Constant(
          value=2,
          lineno=1,
          col_offset=4,
          end_lineno=1,
          end_col_offset=5),
        lineno=1,
        col_offset=0,
        end_lineno=1,
        end_col_offset=5),
      lineno=1,
      👇👇👇
      col_offset=0,
      end_lineno=1,
      end_col_offset=5)],
  type_ignores=[])
```

**Comment by fanninpm** [comment]
@youknowone I think this is good to go; do you?

**Review by youknowone — APPROVED** [review]
Sure, Thank you!

**Pull request merged**
