### PR TITLE
Add test to set.copy

### PR DESCRIPTION
**Pull request by janczer**
I added the silly test. Can someone explane is this test make sens and how I can write more test for this `set`?

### CODE REVIEW

**Comment by adrian17** [comment]
I'm not the oracle here, but I think that
1. this could have been done in Python tests (`set.copy(1.0)`)
2. I don't think it makes sense to test every typechecked function and method there is, for its type checks?
It would need a second opinion though.

**Comment by janczer** [comment]
1. Yes, sure. It could, but in the last PR I got decrease of code coverage. Should we care about test coverage?
2. How I wrote I understand that it's a silly test, and asking about how I can test exactly what `set.copy` do or another functions.

**Comment by windelbouwman** [comment]
This test should indeed be tested by a python snippet. The snippet is shorter, and we test the python parser along (this is not necessarily good btw).

As for the code coverage, I think the python tests should be run when doing the code coverage, the coverage might actually be pretty good when snippets are taken into account.

**Comment by janczer** [comment]
Ok, I see. So I close this PR like unnecessary.

**Pull request closed without merging**
