### PR TITLE
Fix f-string format spec

### LINKED ISSUE #3531: Bad f-string, causing CI issues
#### Code
```python
foo = "bar"
part_spec = ">+#10x"
print(f"{16:0{part_spec}}{foo}")
```

#### CPython
```text
00000+0x10bar
```

#### RustPython
```text
SyntaxError: Got error in f-string: Invalid expression: invalid syntax. Got unexpected token 'part_spec' at line 1 column 9
print(f"{16:0{part_spec}}{foo}")
        ^
```

#### Code
```python
import decimal
width = 10
precision = 4
value = decimal.Decimal('12.34567')
print(f'result: {value:{width}.{precision}}')
```

#### CPython
```text
result:      12.35
```

#### RustPython
```text
SyntaxError: Got error in f-string: Invalid expression: invalid syntax. Got unexpected token '{' at line 1 column 9
print(f'result: {value:{width}.{precision}}')
        ^
```

## Python Documentation

https://docs.python.org/3/reference/lexical_analysis.html#grammar-token-python-grammar-format_spec

@coolreader18 this has been plaguing the CI for the past day or so (because of the `--install-pip` step).

### PR DESCRIPTION
**Pull request by fanninpm**
I was using CPython 3.9's `Lib/test/test_fstring.py` as an implementation guide to track my progress, but there's still a long way to go, particularly w/r/t escape sequences.

Should fix #3531.

### CODE REVIEW

**Comment by fanninpm** [comment]
Now, CI is blocked by `mmap` not being present (c.f. #2059)

**Comment by youknowone** [comment]
is this happened because `get-pip.py` is changed?

**Comment by fanninpm** [comment]
I think that it's because `pip` itself is vendoring dependencies that we currently don't support.

**Comment by youknowone** [comment]
great, thank you!

**Review by youknowone — APPROVED** [review]

**Review by youknowone — APPROVED** [review]
looks good to me, but I am not very familiar with this part. so I want to let a few days for @coolreader18's review.

**Pull request merged**
