### PR TITLE
OSError with filename and filename2

### PR DESCRIPTION
**Pull request by deantvv**
Implement OSError members `filename` and `filename2` by adding a new
struct `IOErrorWithFilename` will implement `IntoPyException`.

This PR will *NOT* pass more CPython test(*) but will allow user to
access `attr:filename` in OSError exception which IMO is a important
feacture.

The reason why CPython test failed before is `AttributeError: 'FileNotFoundError' object has no attribute 'filename'`
After this PR the reason will become `AssertionError: ...`
This is because CPython check the identity of `err.filename` to equal the input `filename` which means the only to pass this test is to store the `filename` object directly into `PyPathLike` or `PathOrFd` and return *the* `filename` if error which is how CPython deal with this with `path_t->object`.

### CODE REVIEW

**Comment by fanninpm** [comment]
> This PR will _NOT_ pass more CPython test(*)

CI is reporting two unexpected successes in `test_urllib`.

**Comment by deantvv** [comment]
> 
> 
> > This PR will _NOT_ pass more CPython test(*)
> 
> CI is reporting two unexpected successes in `test_urllib`.

I missed that. I was too focus on `OSErrorTests::test_oserror_filename`.

I pushed a new commit that made `IOErrorWithFilename` a little bit more useful for letting it to be constructed with `PathOrFd`.

**Comment by youknowone** [comment]
another unexpected success:
```
testOpendir (test.test_fileio.CAutoFileTests) ... unexpected success
```

**Review by youknowone — APPROVED** [review]

**Comment by fanninpm** [comment]
> another unexpected success:
> 
> ```
> testOpendir (test.test_fileio.CAutoFileTests) ... unexpected success
> ```

Only on Windows. Ubuntu and macOS are reporting that as an expected failure. The following snippet may be inserted below the test in question:

```python
# TODO: RUSTPYTHON
if sys.platform == "win32":
    testOpendir = unittest.expectedFailure(testOpendir)
```

**Comment by deantvv** [comment]
Changed as suggested. Hope this time will have a green light.

**Pull request merged**
