### PR TITLE
Add correct method for ImportError.__str__()

### PR DESCRIPTION
**Pull request by fanninpm**

### CODE REVIEW

**Comment by fanninpm** [comment]
I added this as a warmup for adapting `ImportError.__reduce__()`.

**Comment by youknowone** [comment]
by checking CPython's `ImportError_methods`, it only has `__reduce__` as methods. Do we need it because other RustPython side glitches?

**Comment by fanninpm** [comment]
I forgot to check the current behavior of `str(ImportError("msg"))`.

**Comment by fanninpm** [comment]
As it turns out, this seems to be completely unnecessary.

**Pull request closed without merging**
