### PR TITLE
Fix PyStr operations to be safe

### PR DESCRIPTION
**Pull request by youknowone**
ref:
https://github.com/RustPython/RustPython/pull/3066#issuecomment-922493702

### CODE REVIEW

**Review by coolreader18 — APPROVED** [review]
LGTM. Another option for `new_ascii_str` is to depend on https://docs.rs/ascii and take a `&ascii::AsciiStr`, and maybe make some macro that takes a string literal and ensures it's ascii. Or maybe the `assert!(s.is_ascii())` part of `new_ascii_str` could be inlined and resolve by llvm.

**Comment by youknowone** [comment]
I looked in `ascii::AsciiStr` but I couldn't find a compact way to support both `&[u8]` and `&AsciiStr` as `new_ascii_str` input. Instead of it, I renamed `new_ascii_str` to `new_ascii_literal` and changed it to take `&'static [u8]` to inlining it easily can optimize the assertion.

**Comment by coolreader18** [comment]
> I couldn't find a compact way to support both &[u8] and &AsciiStr as new_ascii_str input
I think the key is that we *don't* want to take an arbitrary `&[u8]` - typestate programming and all that, `new_ascii_str` should take an actual, for-sure ascii string so that we don't get any invalid data. For literals we can either do a macro or `.as_ascii_str().unwrap()` at the callsite, which would also get inlined.

**Comment by coolreader18** [comment]
Actually, it wouldn't even need to be a proc macro, it can just use some const fn stuff:
```rust
const fn slice_is_ascii(x: &[u8]) -> bool {
    let mut i = 0;
    while i < x.len() {
        if !x[i].is_ascii() {
            return false
        }
        i += 1;
    }
    true
}

macro_rules! ascii {
    ($x:literal) => {{
        const _: () = {
            ["not ascii"][!slice_is_ascii($x) as usize];
        };
        $x // unsafe { AsciiStr::from_ascii_unchecked($x) }
    }}
}

pub fn foo() -> &'static [u8] {
    ascii!(b"\xff")
}
```
```
error: any use of this value will cause an error
  --> src/lib.rs:15:13
   |
14 | /         const _: () = {
15 | |             ["not ascii"][!slice_is_ascii($x) as usize];
   | |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ index out of bounds: the length is 1 but the index is 1
16 | |         };
   | |__________-
...
22 |       ascii!(b"\xff")
   |       --------------- in this macro invocation
   |
```

**Comment by youknowone** [comment]
`new_ascii_literal` is only used for ascii literals. Do you think we need to use `vm.new_ascii_literal(ascii!("something"))` instead of `vm.new_ascii_literal("something")`?

Probably we can make `vm.new_str<T: IntoPyStr>(s: T)` with `impl AsciiString for IntoPyStr` and `impl String for IntoPyStr` later for more convenient `new_str`, but they will be more useful for variables rather than literals.

**Comment by coolreader18** [comment]
> `vm.new_ascii_literal(ascii!("something"))`

Yeah, I think this is the best option.

**Pull request merged**
