### PR TITLE
Add missing emits for empty statement body in `compile_program_single`

### LINKED ISSUE #3704: Press <enter> with empty line cause **crash** on REPL environment
As the title explained, pressing enter with an empty line causes a crash.
I found a commit(50e6146b235) that makes a crash by searching with `git bisect`.

Here is full rustc version and backtrace log.
### rustc version

```bash
rustc 1.60.0 (7737e0b5c 2022-04-04)
binary: rustc
commit-hash: 7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c
commit-date: 2022-04-04
host: x86_64-unknown-linux-gnu
release: 1.60.0
LLVM version: 14.0.0
```
<details>
  <summary> 

### backtrace log 
</summary>

```bash
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 4294967295', compiler/src/ir.rs:213:28
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_bounds_check
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:85:5
   3: rustpython_compiler_core::ir::stackdepth_push
             at ./compiler/src/ir.rs:213:28
   4: rustpython_compiler_core::ir::CodeInfo::max_stacksize
             at ./compiler/src/ir.rs:206:13
   5: rustpython_compiler_core::ir::CodeInfo::finalize_code
             at ./compiler/src/ir.rs:48:29
   6: rustpython_compiler_core::compile::Compiler::pop_code_object
             at ./compiler/src/compile.rs:285:9
   7: rustpython_compiler_core::compile::compile_impl
             at ./compiler/src/compile.rs:132:16
   8: rustpython_compiler_core::compile::compile_program_single
             at ./compiler/src/compile.rs:158:5
   9: rustpython_compiler_core::compile::compile_top
             at ./compiler/src/compile.rs:111:43
  10: rustpython_compiler::compile
             at ./compiler/porcelain/src/lib.rs:93:5
  11: rustpython_vm::vm::compile::<impl rustpython_vm::vm::VirtualMachine>::compile_with_opts
             at ./vm/src/vm/compile.rs:32:9
  12: rustpython_vm::vm::compile::<impl rustpython_vm::vm::VirtualMachine>::compile
             at ./vm/src/vm/compile.rs:22:9
  13: rustpython::shell::shell_exec
             at ./src/shell.rs:19:11
  14: rustpython::shell::run_shell
             at ./src/shell.rs:90:23
  15: rustpython::run_rustpython
             at ./src/lib.rs:557:9
  16: rustpython::run::{{closure}}
             at ./src/lib.rs:86:41
  17: rustpython_vm::vm::interpreter::Interpreter::run::{{closure}}
             at ./vm/src/vm/interpreter.rs:65:23
  18: rustpython_vm::vm::interpreter::Interpreter::enter::{{closure}}
             at ./vm/src/vm/interpreter.rs:57:39
  19: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panic/unwind_safe.rs:271:9
  20: std::panicking::try::do_call
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  21: __rust_try
  22: std::panicking::try
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  23: std::panic::catch_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  24: rustpython_vm::vm::thread::enter_vm::{{closure}}
             at ./vm/src/vm/thread.rs:12:19
  25: std::thread::local::LocalKey<T>::try_with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:413:16
  26: std::thread::local::LocalKey<T>::with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:389:9
  27: rustpython_vm::vm::thread::enter_vm
             at ./vm/src/vm/thread.rs:10:5
  28: rustpython_vm::vm::interpreter::Interpreter::enter
             at ./vm/src/vm/interpreter.rs:57:9
  29: rustpython_vm::vm::interpreter::Interpreter::run
             at ./vm/src/vm/interpreter.rs:64:9
  30: rustpython::run
             at ./src/lib.rs:86:20
  31: rustpython::main
             at ./src/main.rs:2:5
  32: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

### PR DESCRIPTION
**Pull request by Snowapril**
Compared to previous version of `compile_program_single`, below two
codes are skipped when an empty body is given.
```rust
self.emit_constant(ConstantData::None);
self.emit(Instruction::ReturnValue);
```

Fix #3704

### CODE REVIEW

**Review by youknowone — APPROVED** [review]
Oh, empty line had to return value. it does.

I think emitting ReturnValue (`self.emit(Instruction::ReturnValue)`) part is the primary shared identity of this function.

Instead of adding another retuning in this branch, how about moving the splited part of code to upper if-then branch? Then the code structure will show `ReturnValue` is obviously shared by every branches.

This branch still will have pushing None.

**Comment by Snowapril** [comment]
Oh, Ok I agree. I'll apply that change later and ping you.

**Comment by Snowapril** [comment]
@youknowone  I applied it 😊 Please take a look

**Review by youknowone — APPROVED** [review]
Great, thank you!

**Pull request merged**
