### PR TITLE
Refacter objint

### PR DESCRIPTION
**Pull request by youknowone**
- `objint::get_float_value` -> `objfloat::from_int_value` because objint::get_float_value is only used in objfloat
- `PyInt::cmp`, `PyInt::int_op`, `PyInt::general_op` to make it simple

### CODE REVIEW

**Comment by youknowone** [comment]
Anything more to be merged?

**Comment by coolreader18** [comment]
What do you mean?

**Comment by youknowone** [comment]
Because it is only approved but not merged, so I wonder if you think any further work or review is required.

**Comment by coolreader18** [comment]
Ah no, I think this is good to merge.

**Pull request merged**
