### PR TITLE
Update isclose module of math

### PR DESCRIPTION
**Pull request by Writtic**
- Implement `math.isclose()` function with test case
  - Add `IsCloseArgs` struct for `keyword_only` arguments: `rel_tol`, `abs_tol`
- Change order of test case on `math_module.py` for readability

### CODE REVIEW

**Comment by Writtic** [comment]
Sorry, @coolreader18. 
I erased your comment unintentionally while I fixed it. T-T

**Comment by Writtic** [comment]
I suppose the error of Azure Container is not related to this PR.

**Comment by coolreader18** [comment]
It doesn't look like it, no.

**Comment by coolreader18** [comment]
It's odd that Azure is passing on master, though.

**Comment by Writtic** [comment]
It seems fine now. :grinning:

**Pull request merged**
