### PR TITLE
Add missing 'sysinfoapi' feature for winapi

### PR DESCRIPTION
**Pull request by zaddach**
stdlib doesn't compile on Windows MSVC x64 otherwise.

### CODE REVIEW

**Comment by fanninpm** [comment]
I believe we're in the process of transitioning away from the `winapi` crate towards the `windows` crate.

cc @youknowone

**Review by youknowone — APPROVED** [review]
@zaddach you seem to set git email wrong or at least not same as your github account. Could you check it?

@fanninpm Yes, but I think that's not related to this issue. If we are not going to do it right now, we will want to fix build bug.

**Comment by zaddach** [comment]
@youknowone I've updated the email address in the commits to the one on Github.

**Comment by youknowone** [comment]
Thank you!

**Pull request merged**
