### PR TITLE
Fix test_bool::test_sane_len

### PR DESCRIPTION
**Pull request by youknowone**

### CODE REVIEW

**Comment by youknowone** [comment]
The result is wierd

```
test_sane_len (test.test_bool.BoolTest) ... unexpected success
```
This test is not marked as `expectedFailure` but doesn't show ok. It is success on my local machine so not easy to dig in.

**Comment by youknowone** [comment]
@palaviv do you have any idea about this?

**Comment by palaviv** [comment]
I am not sure what happens here. This test is flaky. I think marking the CPython test suite as allowed failed would be the best until we see this passing consistently.

**Comment by coolreader18** [comment]
Oh, this might be my fault... I panicked when I pushed a commit to master instead of #1666 so I merged it to master right away, but #1666 had apparently broken a CPython test, so I pushed a commit to master last night to fix it.

**Comment by palaviv** [comment]
@youknowone is this rebased in the latest master?

**Comment by youknowone** [comment]
I thought so - but it didn't work. trying again

**Comment by palaviv** [comment]
Seems like everything is OK now :smile:. Can we close this?

**Comment by youknowone** [comment]
I found I fixed another test but didn't change the test decorator. yes, please merge and close this

**Pull request merged**
