### PR TITLE
Add CPython import tests

### PR DESCRIPTION
**Pull request by palaviv**

### CODE REVIEW

**Comment by palaviv** [comment]
Anyone has a mac machine and can help me debug this? Not sure why the tests get stuck...

**Comment by jamestwebber** [comment]
> Anyone has a mac machine and can help me debug this? Not sure why the tests get stuck...

I have a Mac, but haven't tried setting up RustPython on it yet...will try that

**Comment by youknowone** [comment]
@jamestwebber reverting this commit would result error https://github.com/RustPython/RustPython/pull/1963/commits/03cc8eec1e7e6fc74f7c0e7b210f008aeea52a5d

**Comment by jamestwebber** [comment]
> @jamestwebber reverting this commit would result error [03cc8ee](https://github.com/RustPython/RustPython/commit/03cc8eec1e7e6fc74f7c0e7b210f008aeea52a5d)

Well this probably isn't helpful but the test passed for me. I'm on this branch but commented out that line.

However, the _other_ tests aren't passing (failed to import `selenium`), so maybe my setup is not correct.

**Comment by youknowone** [comment]
I tested a bit and it seems mkdir relative path actually has problem even out of python.

- `mkdir /var/folders/yf/dvzgtwmx7bsfgfc2d6mcldvh0000gn/T/tmpgsukx1jw` success
- `mkdir ../../../../var/folders/yf/dvzgtwmx7bsfgfc2d6mcldvh0000gn/T/tmpgsukx1jw` fails

when the upper directory `T` exists and the same

**Comment by palaviv** [comment]
@youknowone the test start hanging when I marked the test as skip. How can a test that does not run be a problem?

**Comment by youknowone** [comment]
I am sorry to be late. I checked out and run this PR, but didn't find any hanging point in local machine.

**Comment by youknowone** [comment]
probably this is not hanging but just hit the timeout

**Comment by youknowone** [comment]
By fixing #2007, I now believe the CI problem here also will be fixed by rebasing it over #2010. Would you try rebase it?

**Comment by palaviv** [comment]
> By fixing #2007, I now believe the CI problem here also will be fixed by rebasing it over #2010. Would you try rebase it?

Thanks. I will try that.

**Pull request merged**
