### PR TITLE
Add test_ipaddress from CPython 3.8

### PR DESCRIPTION
**Pull request by fanninpm**

### CODE REVIEW

**Comment by coolreader18** [comment]
Could you copy over `ipaddress.py` as well? It looks like some of the errors are just caused by the module being older than its tests.

**Comment by coolreader18** [comment]
And then if you want, I think the remaining errors could be fixed by adding a `#[pyfunction] fn index(obj: PyObjectRef, vm: &VirtualMachine) -> PyResult<PyIntRef> { vm.to_index(&obj) }` to `vm/src/stdlib/operator.rs`

**Comment by fanninpm** [comment]
> And then if you want, I think the remaining errors could be fixed by adding a `#[pyfunction] fn index(obj: PyObjectRef, vm: &VirtualMachine) -> PyResult<PyIntRef> { vm.to_index(&obj) }` to `vm/src/stdlib/operator.rs`

The requested changes are coming shortly.

**Comment by coolreader18** [comment]
Ah, alright, I can look into that later.

**Review by coolreader18 — APPROVED** [review]

**Pull request merged**
