### PR TITLE
Fix CI failures with test_subprocess and/or test_os

### PR DESCRIPTION
**Pull request by fanninpm**
As observed in #2652, various tests failed around the time when #2645 and #2647 were both merged into the master branch. Submitting this as draft because I can't reproduce the `test_os` failure on my machine.

### CODE REVIEW

**Review by coolreader18 — APPROVED** [review]

**Comment by fanninpm** [comment]
@coolreader18 would manually triggering the CodeCov workflow somehow fix the `test_os` failure that I couldn't reproduce?

**Comment by coolreader18** [comment]
I could, though I'm not sure that would change anything? Maybe it'd be easier to just cache stat results in `DirEntry`

**Comment by coolreader18** [comment]
I'm just gonna push this small change to master and hope that fixes this issue, I assume it has to do with mtime/atime precision and stuff so hopefully this will avoid all that.

**Comment by coolreader18** [comment]
Or actually no I'll make a PR

**Pull request merged**
