### PR TITLE
Change instance and class to simplified dict type.

### PR DESCRIPTION
**Pull request by windelbouwman**
This is the first step towards proper dictionaries. This work reduces the dependence on fully fledged dictionaries. For now, it takes the assumption that attributes are strings.

This will help later when introducing the order preserving dict.

### CODE REVIEW

**Comment by cthulahoops** [comment]
This breaks this code:

```
>>>>> A = type('A', (object,), {})
>>>>> a = A()
>>>>> a.__dict__ is a.__dict__
False
>>>>> a.__dict__['a'] = 4
>>>>> a.a
Traceback (most recent call last):
  File <unknown>, line 0, in <module>
AttributeError: 'A' object has no attribute 'a'
```

Is this a stepping stone? Do you have a plan to reintroduce real dictionaries later?

**Comment by windelbouwman** [comment]
This change indeed breaks the code you mentioned. This is indeed a stepping stone.

Since the actual dict datatype is more complex than a `HashMap` I would also prefer to use the HashMap for attributes instead of a normal dict. This would break compatibility with CPython, but I think it is better not to touch __dict__.

Never the less, this is a stepping stone. When we have real dictionaries, we can change this back to the usage of proper dictionaries. The main problem is that proper dictionaries require a vm reference to calculate __hash__ and __eq__ and this makes for one great refactor.

**Comment by cthulahoops** [comment]
I think I understand the issue now. We're concerned about ```__hash__``` and ```__eq__``` needing attribute lookups which would in turn require hash lookups (and so on).

The cpython fix for this is that magic methods aren't real dictionary lookups, they are stored in an array with static lookups and stitched together by mappingproxy. We'll want to do this for performance reasons anyway. (I can attack this at some point if you like.)

I'm happy with this a stepping stone, so long as we plan to converge back to CPython.

I'll review the code in detail now.

**Comment by cthulahoops** [comment]
```object.__dict__``` is broken, and I don't know why. It's broken on master to though, so not your fault.

Looks good.

Going to squash merge so the formatting isn't in a separate commit.

**Pull request merged**
