### PR TITLE
Add the _sre module

### PR DESCRIPTION
**Pull request by coolreader18**
So it turns out that [`_sre.py`](https://github.com/nikhaldi/_sre.py) actually is fairly compatible with Python 3's `re`. The `re` and `sre_*` python modules are taken from Python 3.0, but I may be able to use the Python 3.6 ones, I haven't tried yet. I kept the Rust `re` module, but I renamed it to `regex_crate`; I'm not sure if that's a good name or what we should do with it in general.

### CODE REVIEW

**Comment by coolreader18** [comment]
Ok, so there are some issues using the up-to-date Python sre modules with `_sre.py`, but we just need to implement a few missing sre opcodes, which is doable. I'll split that off into a separate branch. (The 2 most recent commits are from my work on it).

**Comment by coolreader18** [comment]
I think I'd eventually like to split this off into a separate repository so that other WIP Python implementations can easily get a pure-Python fully functioning `re` implementation.

**Comment by coolreader18** [comment]
Never mind, I was able to use the CPython 3.6 versions, it was a tiny bug in another method that was causing it to fail.

**Comment by windelbouwman** [comment]
Nice work!

**Pull request merged**
