### PR TITLE
Remove not very useful iterator utilty functions

### PR DESCRIPTION
**Pull request by youknowone**
based on #3183

### CODE REVIEW

**Comment by DimitrisJim** [comment]
Right, was going to ask, does this supersede #3183 or are you still planning on merging that too?

**Comment by youknowone** [comment]
either way ok by review convenience

**Review by DimitrisJim — APPROVED** [review]
looks great to me, quick timings show me there's also a _slight_ performance gain too.

**Comment by youknowone** [comment]
yes, though it is just a little bit

**Pull request merged**
