### PR TITLE
Fix writing to stdio streams on Windows

### LINKED ISSUE #1753: print to sys.stderr not working on Windows
```py
print("Error", file=sys.stderr)
```
Currently causes the following error:
```py
Traceback (most recent call last):
  File "D:\a\RustPython\RustPython\tests\snippets\printing.py", line 19, in <module>
    print("Error", file=sys.stderr)
OSError: The handle is invalid. (os error 6)
```

### PR DESCRIPTION
**Pull request by coolreader18**
~~Just testing this on CI right now, I'm not sure if this will work.~~ Fixes #1753

### CODE REVIEW

**Comment by coolreader18** [comment]
I'm not sure, you said that there were other issues involved with doing that as well? I could try it on a windows machine today and see what issues there are.

**Comment by coolreader18** [comment]
@palaviv yep! Just a few small changes and the CPython tests work on windows!

**Comment by coolreader18** [comment]
Hmmm. It worked on my machine.

**Comment by palaviv** [comment]
> Hmmm. It worked on my machine.

Let's push the streams fix without enabling the test and try to fix that in another PR.

**Pull request merged**
