### PR TITLE
Feature/round

### PR DESCRIPTION
**Pull request by JimJeon**
Fixed feature `round`

- builtin round
- int round
- float round (Only implemented when `ndigits` is 0)

### CODE REVIEW

**Comment by JimJeon** [comment]
@windelbouwman Could you review this Pull Request?

**Comment by windelbouwman** [comment]
@JimJeon sorry for the slow review. Looks good to me!

**Comment by youknowone** [comment]
This issue was a blocker for ouroboros datetime

**Comment by JimJeon** [comment]
@windelbouwman @youknowone thanks all!

**Pull request merged**
