### PR TITLE
WIP: Drop unused IntoPyNativeFunc impl

### PR DESCRIPTION
**Pull request by adrian17**
Should fix latest nightly breakages.

### CODE REVIEW

**Comment by adrian17** [comment]
...I didn't except this to fail for wasm. Let's go back to the drawing board and/or wait for Rust folks to give some advice.

**Comment by coolreader18** [comment]
Maybe to fix WASM, you could `impl FromArgs for PyFuncArgs` and then make `print_fn` a `Fn(PyFuncArgs, &VirtualMachine)`.

**Comment by windelbouwman** [comment]
@adrian17 what do you wish to do with this PR?

**Comment by adrian17** [comment]
For now, let's just wait. It's the nature of Nightly that things can break periodically, and we shouldn't really try fixing our code as soon as this happens. Let's just give the situation some time to clarify itself, especially now that the Rustc bug just got some activity.
I'd also consider moving Nightly-dependent builds to "allowed failures" on Travis.

**Comment by adrian17** [comment]
PS oh wait, now it's breaking on Beta too? Huh.
Anyway, I'd still wait a little more. Will take a look at it tomorrow, if the issue persists.

**Comment by windelbouwman** [comment]
If the issue persists, we should disable the nightly build, to prevent that we miss other regressions.

**Pull request closed without merging**
