### PR TITLE
Relocate `vm.rich_compare` to `obj.rich_compare`

### PR DESCRIPTION
**Pull request by Limits0x**
Fixes task 4 of #3324

### CODE REVIEW

**Comment by AP2008** [comment]
This branch cannot be merged ? How do I view and fix the merge conflicts ?

**Comment by AP2008** [comment]
@Snowapril Is this fine ? Can you review it ?

**Comment by Snowapril** [comment]
Uh... It seems something going wrong. first of all, merge commit must not be in the PR.
your branch have `_hash`  but main branch do not have it. this conflict is main cause of blocking.

general rebasing process for resolving conflict is something like this.
1. git fetch upstream main
2. git rebase upstream/main (then there will be conflict codes in `vm.rs`, in this case, you need to remove both of them)
3. (after solving conflict) git add vm/src/vm.rs
4. git rebase --continue
5. git push origin relocate-rich_compare -f

**Comment by Snowapril** [comment]
you also need to drop merge commit (which is top of your branch currently)

**Comment by AP2008** [comment]
@Snowapril I followed the steps you provided and also dropped the merge commit. Is it fine now ?

**Comment by Snowapril** [comment]
Oh! it seems perfect now! Great job 😊

**Pull request merged**
