### PR TITLE
Set trace_func / profile_func to none on error

### PR DESCRIPTION
**Pull request by matthew-hagemann**
#4906

trace_func and profile_func now set to none if errors are encountered

Working with the example code:
```
import sys
def trace(frame, event, arg):
    raise NameError
    return trace

sys.settrace(trace)
print("fail here")
try:
    a = 1/0
except:
    print("not allowed")
```
RustPython now correctly will print:
fail here
not allowed

### CODE REVIEW

**Comment by DimitrisJim** [comment]
thanks! there's a couple of tests that appear to now succeed:

```bash
UNEXPECTED SUCCESS: test_run_as_module (test.test_trace.TestCommandLine.test_run_as_module)
UNEXPECTED SUCCESS: test_sys_argv_list (test.test_trace.TestCommandLine.test_sys_argv_list)
UNEXPECTED SUCCESS: test_arg_errors (test.test_trace.TestFuncs.test_arg_errors)
```

if you haven't done it previously. You can open the relevant file (`Lib/test/test_trace.py`) and remove the decorator and that currently states that the test is expected to fail. For example for `test_arg_errors` the change should be:

```python
# TODO: RUSTPYTHON, gc
@unittest.expectedFailure
def test_arg_errors(self):
    # Function body
```

into:

```python
def test_arg_errors(self):
    # Function body
```

**Comment by matthew-hagemann** [comment]
Thanks for the help, I have updated those tests 👍

**Comment by fanninpm** [comment]
@xiaxinmeng Does this fix the issue you were having?

**Review by youknowone — APPROVED** [review]
Thank you so much!

**Pull request merged**
