### PR TITLE
Object protocol

### PR DESCRIPTION
**Pull request by youknowone**
I also suggest to replace the paired vm methods and use PyObjectRef methods

ref #3244

### CODE REVIEW

**Comment by DimitrisJim** [comment]
should `ItemProtocol` be moved here too?

**Comment by youknowone** [comment]
Probably. I doub't we really need that trait now. I think relocating `impl ItemProtocol for PyObjectRef` to here, `impl ItemProtocol for PyDictRef` to its `impl` and removing the trait could be better than now.

**Comment by DimitrisJim** [comment]
The `delitem/setitem/getitem` in `PyDict` would need to also be made public so objects that are known to be dicts to be able to call directly into them.

**Comment by youknowone** [comment]
@DimitrisJim could you review it? I want to open issue for relocating functino bodies and refactoring around them.

**Pull request merged**
