### PR TITLE
Make `type()` bases arg only take tuples

### PR DESCRIPTION
**Pull request by carbotaniuman**

### CODE REVIEW

**Comment by coolreader18** [comment]
You can call `.borrow_value()` on the tuple to get a `&[PyObjectRef]`, and then use that instead of the PyIterable

**Comment by coolreader18** [comment]
Oh I see, cause it has to be `Vec<PyTypeRef>`. Maybe just `.borrow_value().iter().map(typeref tryfromobject).collect::<PyResult<Vec<PyTypeRef>>()?`

**Comment by coolreader18** [comment]
I recently added a `builtins::tuple::PyTupleTyped` type, you could try making the type of `bases: PyTupleTyped<PyTypeRef>`

**Comment by carbotaniuman** [comment]
Updated. Is there a reason you added the `Transmute...` trait instead of just `TryFromObject`?

**Comment by coolreader18** [comment]
`TryFromObject` is implemented for a ton of different types and doesn't have any invariants regarding representation, e.g. if it just required TryFromObject you could have `PyTupleTyped<u8>`, and that obviously wouldn't be safe to cast `PyObjectRef` to `u8`. `TransmuteFromObject` is an `unsafe trait`, so if anyone wants to implement it wrong they have to use `unsafe` to do so :upside_down_face:

**Review by coolreader18 — APPROVED** [review]
Thanks for contributing!

**Pull request merged**
