### PR TITLE
Float type: Added __doc__

### PR DESCRIPTION
**Pull request by ZapAnton**

### CODE REVIEW

**Comment by ZapAnton** [comment]
@windelbouwman the cpython check fails, because of the version conflict.

I have Python 3.7, in which the `float.__doc__` contains `Convert a string or number to a floating point number, if possible.`, but the Travis check uses the Python 3.6 version in which `float.__doc__` contains 
`float(x) -> floating point number\n\nConvert a string or number to a floating point number, if possible`.

What version should be chosen here?

**Comment by veera83372** [comment]
For most of the types `__doc__` string is different from python 3.7 to 3.6
Please decide that ASAP

**Comment by windelbouwman** [comment]
I would not test the docstrings and take the latest from python 3.7. This is probably most accurate. Note that we might choose our docstrings from being different (if this means more clear / better) than CPython. The aim of rustpython is not per se 100% compatibility with cpython.

**Comment by ZapAnton** [comment]
@windelbouwman I will then remove the latest commit.
Would you like to remove all other `__doc__` tests (e.g. for bool) in the separate PR?

**Comment by ZapAnton** [comment]
Done

**Comment by windelbouwman** [comment]
It would be good to remove too strict tests on doc strings such that they work on both CPython 3.7 and CPython 3.6.

**Pull request merged**
