### PR TITLE
feat(argparse): update to 3.11

### PR DESCRIPTION
**Pull request by carlosmiei**
- Imported lib from: https://github.com/python/cpython/blob/3.11/Lib/argparse.py
- Imported test from: https://github.com/python/cpython/blob/3.11/Lib/test/test_argparse.py

Ran the tests and seemed ok

```
RUSTPYTHONPATH=Lib cargo run --release Lib/test/test_argparse.py 
    Updating git repository `https://github.com/youknowone/unicode_names2.git`
    Finished release [optimized] target(s) in 0.84s
     Running `target/release/rustpython Lib/test/test_argparse.py`
(...)
----------------------------------------------------------------------
Ran 1698 tests in 5.036s

OK
```

### CODE REVIEW

**Review by fanninpm — APPROVED** [review]
LGTM.

For future reference, I believe you can use the following command to test your changes locally (in a manner similar to RustPython's CI):

```shell
# this runs all of the tests (not necessary if you know which test is affected)
cargo run --release --features ssl,jit -- -m test -j 1 -u all --slowest --fail-env-changed -v
# this runs only the test suite named "test_whatever" (usually located at `Lib/test/test_whatever.py`)
cargo run --release --features ssl,jit -- -m test -j 1 -u all --slowest --fail-env-changed -v test_whatever
```

For a list of all resources and more command-line options, you can execute `cargo run --release --features ssl,jit -- -m test -h`.

**Comment by youknowone** [comment]
We'd better to add the commands to the issue.

**Comment by youknowone** [comment]
Thank you!

**Comment by carlosmiei** [comment]
> LGTM.
> 
> For future reference, I believe you can use the following command to test your changes locally (in a manner similar to RustPython's CI):
> 
> ```shell
> # this runs all of the tests (not necessary if you know which test is affected)
> cargo run --release --features ssl,jit -- -m test -j 1 -u all --slowest --fail-env-changed -v
> # this runs only the test suite named "test_whatever" (usually located at `Lib/test/test_whatever.py`)
> cargo run --release --features ssl,jit -- -m test -j 1 -u all --slowest --fail-env-changed -v test_whatever
> ```
> 
> For a list of all resources and more command-line options, you can execute `cargo run --release --features ssl,jit -- -m test -h`.

@fanninpm Thanks, I was not aware of that command 🙂

**Pull request merged**
