### PR TITLE
Add zoneinfo Library from Python 3.12.6

### PR DESCRIPTION
**Pull request by rroblf01**
In this PR I have added zoneinfo with the corresponding test suite.

### CODE REVIEW

**Comment by rroblf01** [comment]
> Thank you so much for contributing! Just one more thing. Could you check which Python version did you brought the library from?

Good afternoon,
This library was introduced as is in 3.11, but it is compatible with 3.12 and so far with what has been developed for python 3.13.0rc2

**Comment by youknowone** [comment]
Do you mean you copied them from 3.13.0rc2? That's for record purpose. We usually leave version information the copied version for later.

**Comment by rroblf01** [comment]
> Do you mean you copied them from 3.13.0rc2? That's for record purpose. We usually leave version information the copied version for later.

Hello,

I prefer to say that it is taken from python 3.12.6.

**Comment by youknowone** [comment]
Thank you for confirming!
And welcome to the project.

**Pull request merged**
