### PR TITLE
Add `co_names` to `PyCode`

### PR DESCRIPTION
**Pull request by jopemachine**
# Outline

Add `co_names` to `PyCode`

CPython document says `co_names` is a *tuple of names other than arguments and function locals*

## Reference

https://github.com/python/cpython/blob/main/Doc/library/inspect.rst#types-and-members

## Result

```
>>>>> a = 3
>>>>> b = 5
>>>>> c = 7
>>>>> def f(k, l, m):
.....   d = 9
.....   return a + k
..... 
>>>>> f.__code__.co_names
1
('a',)
>>>>> 
```

### CODE REVIEW

**Comment by youknowone** [comment]
if there is no related unittest in `Lib/tests`, could you add the test you used in this issue to somewhere in `extra_tests/snippets`?

**Comment by Snowapril** [comment]
Oh, It seems we missed `Lib/code.py` from cpython. We'd better use it
https://github.com/python/cpython/blob/main/Lib/code.py

**Comment by youknowone** [comment]
@Snowapril is it related to this changes?

**Comment by Snowapril** [comment]
I'm sorry. I uploaded a different link 😂 Please take a look again @jopemachine

**Comment by jopemachine** [comment]
I updated the `test_code.py`, but there are some points that I'd like to mention.

* Updated `opcode.py` for updating `test_code.py`. but I didn't update test_opcode.py because test code is not changed.
* There are some `dump` function calls in the above comment of the `test_code.py`. Because this raised test failure, I commented it out and added `TODO: RUSTPYTHON` comment.
* I checked the added `co_names` manually in the dump call, the first dump call's actual result is different from the expected result. The actual result is `('__doc__')` while the expected result is empty tuple, the remaining tests result are correct.

**Review by youknowone — APPROVED** [review]
Great! thank you!

**Pull request merged**
