### PR TITLE
Add __floor__ and __ceil__ to float w/ tests

### PR DESCRIPTION
**Pull request by fanninpm**

### CODE REVIEW

**Comment by fanninpm** [comment]
Closing as this was not present in CPython 3.8

**Comment by coolreader18** [comment]
Oh, it's fine to use stuff from CPython 3.9, if you want to reopen this. We have self-describing fstring specifiers and `:=` as well from 3.9.

**Comment by coolreader18** [comment]
Oh, unless there's a issue with CI tests, it seems weird that the test snippets would be affected.

**Comment by coolreader18** [comment]
I suppose you could probably comment out the AttributeError test in stdlib_math

**Pull request closed without merging**
