### PR TITLE
Update unittest from CPython 3.10.5

### PR DESCRIPTION
**Pull request by youknowone**
This is not done yet.

tracker for many related issues

### CODE REVIEW

**Comment by youknowone** [comment]
```
======================================================================
ERROR: test_getproxies_environment_prefer_lowercase (test.test_urllib.ProxyTests_withOrderedEnv)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/user/Projects/RustPython/vm/pylib-crate/Lib/test/test_urllib.py", line 313, in setUp
    os.environ = collections.OrderedDict()
  File "/Users/user/Projects/RustPython/vm/pylib-crate/Lib/collections/__init__.py", line 132, in __init__
    self.__update(*args, **kwds)
  File "/Users/user/Projects/RustPython/vm/pylib-crate/Lib/_collections_abc.py", line 989, in update
    if isinstance(other, Mapping):
  File "/Users/user/Projects/RustPython/vm/pylib-crate/Lib/_py_abc.py", line 105, in __instancecheck__
    return cls.__subclasscheck__(subclass)
  File "/Users/user/Projects/RustPython/vm/pylib-crate/Lib/_py_abc.py", line 142, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/Users/user/Projects/RustPython/vm/pylib-crate/Lib/_py_abc.py", line 123, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "/Users/user/Projects/RustPython/vm/pylib-crate/Lib/typing.py", line 1564, in _proto_hook
    raise TypeError("Instance and class checks can only be used with"
TypeError: Instance and class checks can only be used with @runtime_checkable protocols


8 tests failed:
    test_support test_unittest test_urllib test_userdict test_uuid
    test_webbrowser test_xmlrpc test_yield_from

3 tests skipped:
    test_socketserver test_urllib2net test_urllibnet
```

**Comment by fanninpm** [comment]
> Likely blocked on #2999

**Comment by youknowone** [comment]
I commented out `async for` code

**Comment by fanninpm** [comment]
It might be worth taking a look at #2513.

**Pull request merged**
