### PR TITLE
Type mro

### PR DESCRIPTION
**Pull request by cthulahoops**
Fix this:

```
>>>>> type.__mro__
Traceback (most recent call last):
  File <stdin>, line 0, in <module>
TypeError: Expected type <class 'type'>, not <class 'NoneType'>
```

### CODE REVIEW

**Comment by cthulahoops** [comment]
Took me a while to figure out why I couldn't get the property to type check.

@skinny121 I think this is a bug in the PropertyBuilder?

**Comment by skinny121** [comment]
I wanted to make it typesafe so the type of the value returned from 'get' must equal the type 'set' accepted. But it seems to just gets in the way.

**Comment by cthulahoops** [comment]
I thought I'd tried that. (I blame the error messages.)

I can get it to work by making the getter return PyTupleRef instead of PyTuple (adds some noise to the getter). I'd like to just have the setter take PyTuple but get blocked by: 

```
the trait `pyobject::TryFromObject` is not implemented for `obj::objtuple::PyTuple`
```

So, I guess implementing that would work.

I think we want ```PyObjectRef``` in this case anyway, as we want a TypeError complaining about trying to set a read-only attribute, not a TypeError about trying to set it to the wrong type.

**Comment by windelbouwman** [comment]
Strange change, looks like a hack around some other issue in the property factory. We need to take a look at this.

**Pull request merged**
