### PR TITLE
Created macro to construct keywords inorder to enforce DRY principle

### PR DESCRIPTION
**Pull request by matrizx**

### CODE REVIEW

**Comment by matrizx** [comment]
Cargo fmt failed, but it looks more readable with it.
Without: `"...", Tok::Ellipsis`
With: 
`"...",`
`Tok::Ellipsis`

**Comment by cthulahoops** [comment]
Would we better using a generic hash literal macro here, rather than rolling our own for this specific case?

Something like: https://docs.rs/maplit/1.0.1/maplit/

I hope it would also solve the formatting issue, and there's lots of places that would benefit from this type of change.

**Comment by matrizx** [comment]
> Would we better using a generic hash literal macro here, rather than rolling our own for this specific case?
> 
> Something like: https://docs.rs/maplit/1.0.1/maplit/
> 
> I hope it would also solve the formatting issue, and there's lots of places that would benefit from this type of change.

Sounds good to me. Want me to do it? I could use some help with seeing where you want it applied but other than that I could take this on :)

**Comment by cthulahoops** [comment]
I think there's fewer places than I was thinking - I was picturing things like objcode.rs where I wrote a loop to handle this repetition, but in that case the HashMap is created elsewhere and I'm just adding a bunch of elements.

Just use the maplit macro here, and then we can use it in other places as we find them.

**Comment by windelbouwman** [comment]
I'm not a huge fan of this change. It introduces either a macro, or a macro in a crate. What is wrong with the original code?

**Comment by matrizx** [comment]
@windelbouwman for more readable code, and so it can be reused later for more keyword construction. Not necessary, but looks better to read.

**Comment by cthulahoops** [comment]
I'm far more pro-macro than Windel. We use the ```vec!``` macro widely and the code would be much noisier without it. This feels like the same thing. I'd much rather read the version with ```hashmap!```, than a list of repeated inserts.

I don't this version because I'd like a general macro rather than a one-off for this case.

@matrizx do you want to write the version with the hashmap! macro so we can see how it looks?

**Comment by windelbouwman** [comment]
Okay, if both of you are in favor, lets do this change :)

**Comment by matrizx** [comment]
@cthulahoops No problem : ) I'll do it right now.

**Pull request closed without merging**
