### PR TITLE
unexpected success on local

### PR DESCRIPTION
**Pull request by tobark**

### CODE REVIEW

**Comment by youknowone** [comment]
@coolreader18 The weird thing here is, why it isn't catched by CI.

**Comment by coolreader18** [comment]
Yeah, that is really weird. It wasn't failing on master before this?

**Comment by youknowone** [comment]
yep, no failing. would there be any case of silience failure of unittest?

**Comment by coolreader18** [comment]
Idk, maybe an unexpected success doesn't actually cause it to fail? Though I swear it has caused a ci failure before

**Pull request merged**
