### PR TITLE
 Add json output for CPython tests

### PR DESCRIPTION
**Pull request by coolreader18**
Related to #1671

### CODE REVIEW

**Comment by ep12** [comment]
See #1838 (example section):
This pr implements the code object `co_varnames` attribute, but the value differs from the ones cpython and pypy present...

**Comment by abitrolly** [comment]
Does it produce the result in real-time, or only after the processing is finished?

Is it a custom format, or something like https://chromium.googlesource.com/chromium/src.git/+/master/docs/testing/json_test_results_format.md was used for an inspiration?

**Comment by coolreader18** [comment]
@abitrolly I'm not sure what you mean by your first question, but as to your second I think it's basically just the data that `unittest` outputs itself, converted to JSON. I didn't write the runner myself, I modified it from https://github.com/agramian/custom-text-test-runner.

**Comment by coolreader18** [comment]
@ep12 I'll look into fixing co_varnames separately.

**Pull request merged**
