### PR TITLE
Add test_range from cpython 3.8.7

### PR DESCRIPTION
**Pull request by ishigoya**

### CODE REVIEW

**Comment by fanninpm** [comment]
I see that you're using your master branch as a feature branch. How's that working out for you?

**Comment by ishigoya** [comment]
When I only have one PR on the go, no problem!

I do most of my messing about on a local git server, so pushing through github is the slightly awkward last step :smile:

**Comment by fanninpm** [comment]
> pushing through github is the slightly awkward last step smile

The [GitHub CLI](https://cli.github.com/) has actually helped me out with that last step. I'd definitely recommend it.

**Comment by ishigoya** [comment]
Thanks, I'll have a look!

**Review by coolreader18 — APPROVED** [review]
Thank you for contributing!

**Pull request merged**
