### PR TITLE
Fix range attributes type

### LINKED ISSUE #3952: `range` attributes type
## Feature

Implement `range` 's boolean argument

## Python Documentation

https://docs.python.org/3/library/stdtypes.html?highlight=range#ranges

## Relevant Test Case

https://github.com/RustPython/RustPython/pull/3910/files#diff-34ede011e3fd5660af3db245be7bd645d4c15fac138b477ac4be9be57ae5d30cR667-R668

### PR DESCRIPTION
**Pull request by daeun503**
Fix #3952

### CODE REVIEW

**Comment by daeun503** [comment]
According to [this cpython commit](https://github.com/daeun503/cpython/commit/5f4b229df7812f1788287095eb6b138bb21876a4#diff-e523221c4331dc96024d5c3a51a1c0d8ef2d11aa4ff0429d9fa286d054189bbb), `test_range.py` has been updated, but `test_copy.py` has not been updated.

After I modified the code, I failed in `test_deepcopy_range`. 
So I updated `test_copy.py` for the above reason. Is this right ??

1. deleted `test_deepcopy_range`.
2. Added @`unittest.expectedFailure` to `test_deepcopy_atomic`
: Because deepcopy of `range(10)` fails before and after I modify the code.

**Comment by youknowone** [comment]
To update test files, you can check this guideline: https://github.com/RustPython/RustPython/wiki/How-to-update-test-files

**Review by youknowone — CHANGES_REQUESTED** [review]
Please make separated commits about `test_copy.py` by following the guideline. Everything other is looking great! Thank you!

**Review by youknowone — APPROVED** [review]

**Comment by daeun503** [comment]
> Please make separated commits about test_copy.py by following the guideline. Everything other is looking great! Thank you!

I separated `test_copy.py`. And... added `support.gc_collect()` according to CPython v3.10.5.
Thanks!

**Comment by youknowone** [comment]
Thank you for contributing!

**Pull request merged**
