### PR TITLE
Added csv module

### PR DESCRIPTION
**Pull request by kluid**
Hey, I just added csv module and 'reader' function which implements '__iter__' and '__next__' methods.
**TODO**: impl 'writer'

### CODE REVIEW

**Comment by youknowone** [comment]
It seems adding `Lib/csv.py` will solve to problem

**Comment by kluid** [comment]
Thanks, I fixed test failure and rebased commits.

**Comment by youknowone** [comment]
The added `csv.py` file is not same as cpython 3.7.4 https://github.com/RustPython/RustPython/pull/1474/commits/1b2edb83627d4825e50f49cf7c826c2f23ac80f4#diff-68621ddf30e71a01a3c4994afe09d2bdR7

Will you split commits by copying `csv.py` from cpython and editing it for rustpython to make easy to track rustpython-specific changes?

**Comment by kluid** [comment]
Sorry, it was mistake. I splitted that commits.

**Comment by youknowone** [comment]
@kluid did you close this pr by accident? because it seemed there was no comment or reason to close this, i want to check it.

**Comment by kluid** [comment]
@youknowone Oh, Sorry. I did not wanted make you get worried about it. I did not wanted make long history of this issue. I'm WIP again. ;)
I'll make a new PR of this issue.

**Pull request closed without merging**
