### PR TITLE
Refactor making union parameters 

### PR DESCRIPTION
**Pull request by TwoPair**
#4035

### CODE REVIEW

**Comment by youknowone** [comment]
would you also replace unwrap to `?` please? that will cause crash which usually we don't want

**Comment by TwoPair** [comment]
> would you also replace unwrap to `?` please? that will cause crash which usually we don't want

If I did that, I shoud do refactoring every parts using `dedup_and_flatten_args` function.
Is that really what you intend?

**Comment by youknowone** [comment]
ah, ok, maybe that's not expected to be failed. `.unwrap()` -> `.expect("types are always comparable")` will be enough

**Review by youknowone — APPROVED** [review]
Thank you!

**Pull request merged**
