### PR TITLE
Remove NewLineHandler, move handling inline.

### PR DESCRIPTION
**Pull request by DimitrisJim**
Removes the new line handler window and moves the checks inside the lexer. This is slightly more complex but it does mean we don't check each source character twice (once during the NewLineHandler and once during the proper lexing phase. This does result in an 7-8% speed-up on my machine.

I've also gone ahead and documented most I could in the file.

### CODE REVIEW

**Comment by DimitrisJim** [comment]
@charliermarsh if you could run ruff against this before we decide on merging it would be great.

**Comment by charliermarsh** [comment]
Before:

Screen Shot 2023-02-08 at 10 50 42 AM

After:

Screen Shot 2023-02-08 at 10 56 14 AM

**Comment by charliermarsh** [comment]
A nice improvement :)

**Comment by charliermarsh** [comment]
(All tests pass too.)

**Comment by DimitrisJim** [comment]
Great, this change would also make it easier to support #4468 (though having a clean way to do it would still need some thought) since the lexer would see every single character of the source.

**Review by youknowone — APPROVED** [review]

**Pull request merged**
