### PR TITLE
Implement os.getgrouplist

### PR DESCRIPTION
**Pull request by kenkoooo**
Implement `os.getgrouplist`.

Ref #1175 

### Question
Looks like we don't have [test_posix.py](https://github.com/python/cpython/blob/49926cf/Lib/test/test_posix.py) to check `os.getgrouplist`. Do we want to copy it from `CPython`?

### CODE REVIEW

**Comment by kenkoooo** [comment]
Looks like we don't have [test_posix.py](https://github.com/python/cpython/blob/49926cf/Lib/test/test_posix.py) to check `os.getgrouplist`. Do we want to copy it from `CPython`?

**Comment by coolreader18** [comment]
Yeah, I think that'd be good! You can follow [this blog post](https://rustpython.github.io/guideline/2020/04/04/how-to-contribute-by-cpython-unittest.html) to add the unittest file.

**Comment by kenkoooo** [comment]
Thanks. Let me do that.

**Comment by kenkoooo** [comment]
@coolreader18 I copied `test_posix.py` and edited it as the following:
- Put `expectedFailure` to unimplemented features.
- Put `skip` to 1 test, which causes `panic`.
- Put `skip` to 1 class, which is an unimplemented macOS feature.

And also I formatted `bytecode/src/lib.rs` and `compiler/src/ir.rs` to follow the latest `rustfmt`, but we still need to fix a lot of places to follow the latest `clippy`. I guess we want to fix them in another PR.

**Review by coolreader18 — APPROVED** [review]
Thank you for contributing!

**Pull request merged**
