### PR TITLE
Enable Zero-padding with Format Strings

### LINKED ISSUE #1379: wrong str.format()
i=1
print(f'{i:04d}')

prints 1 instead of 0001

### PR DESCRIPTION
**Pull request by j30ng**
Hi! This patch is an attempt to fix #1379 

References
* https://www.python.org/dev/peps/pep-3101/
* https://github.com/python/cpython/blob/v3.7.4/Python/formatter_unicode.c#L219-L225

### CODE REVIEW

**Comment by windelbouwman** [comment]
This looks good to me, could you add the test case as mentioned in #1379 as a test snippet as well? You also might want to rebase upon the master branch to fix the windows build.

**Comment by j30ng** [comment]
Rebasing is done, and I added the testcase, although the CI build seems to be failing due to some unrelated issues.

**Comment by coolreader18** [comment]
Hmm, I'm guessing that's because the new Rust version that just got released comes with some changes to rustfmt/clippy. I know it's not related, but would you be able to upgrade your rustfmt version and fix the issues?

**Comment by j30ng** [comment]
@coolreader18 Sure thing.

**Pull request merged**
