### PR TITLE
Reorganize os module

### PR DESCRIPTION
**Pull request by youknowone**
This PR re-cluster os module with 3 submodules `posix`, `nt` and `minor`.
I think current result is not the ideal state but this was limit for me due to lack of windows dev enviroment.

### CODE REVIEW

**Comment by youknowone** [comment]
Sorry, I am not aware of that topic at all. Is it a debug info problem or could it make an actual bug?

**Comment by coolreader18** [comment]
I'm not sure exactly, I haven't actually seen an issue for it in rust-lang/rust, but there was some stuff in the latest version related to proc macros. Does the issue with error locations not showing up still happen?

**Comment by youknowone** [comment]
When signature is wrong,

for pyfunction:
```
(RustPython) ➜  RustPython git:(master) ✗ cargo build
    Blocking waiting for file lock on build directory
   Compiling rustpython-vm v0.1.2 (//RustPython/vm)
error[E0277]: the trait bound `for<'r> fn(&'r vm::VirtualMachine, function::OptionalArg<pyobject::PyRef<obj::objstr::PyString>>) -> std::result::Result<std::sync::Arc<pyobject::PyObject<(dyn pyobject::PyObjectPayload + 'static)>>, pyobject::PyRef<exceptions::PyBaseException>> {stdlib::os::_os::error}: function::IntoPyNativeFunc<_, _, _>` is not satisfied
   --> vm/src/stdlib/os.rs:277:8
    |
277 |     fn error(vm: &VirtualMachine, message: OptionalArg<PyStringRef>) -> PyResult {
    |        ^^^^^ the trait `function::IntoPyNativeFunc<_, _, _>` is not implemented for `for<'r> fn(&'r vm::VirtualMachine, function::OptionalArg<pyobject::PyRef<obj::objstr::PyString>>) -> std::result::Result<std::sync::Arc<pyobject::PyObject<(dyn pyobject::PyObjectPayload + 'static)>>, pyobject::PyRef<exceptions::PyBaseException>> {stdlib::os::_os::error}`

error: aborting due to previous error
```

For inner class method:
```
(RustPython) ➜  RustPython git:(master) ✗ cargo build
    Blocking waiting for file lock on build directory
   Compiling rustpython-vm v0.1.2 (//RustPython/vm)
error[E0277]: the trait bound `for<'r> fn(stdlib::os::_os::DirEntry, stdlib::os::FollowSymlinks, &'r vm::VirtualMachine) -> std::result::Result<bool, pyobject::PyRef<exceptions::PyBaseException>> {stdlib::os::_os::DirEntry::is_dir}: function::IntoPyNativeFunc<_, _, _>` is not satisfied
   --> vm/src/stdlib/os.rs:435:12
    |
435 |         fn is_dir(self, follow_symlinks: FollowSymlinks, vm: &VirtualMachine) -> PyResult<bool> {
    |            ^^^^^^ the trait `function::IntoPyNativeFunc<_, _, _>` is not implemented for `for<'r> fn(stdlib::os::_os::DirEntry, stdlib::os::FollowSymlinks, &'r vm::VirtualMachine) -> std::result::Result<bool, pyobject::PyRef<exceptions::PyBaseException>> {stdlib::os::_os::DirEntry::is_dir}`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `rustpython-vm`.

To learn more, run the command again with --verbose.
```

I have no idea what kind of error was in that comment.

**Comment by youknowone** [comment]
@palaviv any idea how to make the untrackable error?

**Comment by youknowone** [comment]
Go for this and let's see how things go. Even when it has problem, it doesn't look commonly making very serious issue, and it will be eventually solved by rust itself.

**Pull request merged**
