### PR TITLE
Another temporary fix for #4566 

### LINKED ISSUE #4566: Some valid named unicode characters cause syntax errors
`"\N{BACKSPACE}another cool trick"` yields a syntax error in RustPython, but runs without error on CPython.

See: https://github.com/charliermarsh/ruff/issues/3207.

### PR DESCRIPTION
**Pull request by youknowone**
see also #4572

we can temporarily go with this because unicode_names2 will work with this interface in future.

closes #4566

### CODE REVIEW

**Review by DimitrisJim — APPROVED** [review]

**Comment by youknowone** [comment]
Oh, no. The UnicodeData.txt does include aliases but not abbrs.

**Comment by DimitrisJim** [comment]
ah, that's true, I hadn't noticed that either tbh (and really annoying unfortunately since you now need to handle both files.)

**Comment by DimitrisJim** [comment]
does your branch of unicode_names2 currently handle the abbreviations? If so, lets merge it.

**Comment by youknowone** [comment]
Yes, finally.

**Pull request merged**
