### PR TITLE
prettier *.js + fix miri build

### PR DESCRIPTION
**Pull request by youknowone**

### CODE REVIEW

**Review by zanieb — APPROVED** [review]

**Comment by zanieb** [comment]
Oh no it didn't work https://github.com/RustPython/RustPython/actions/runs/5599936124/jobs/10241587790?pr=5028

**Comment by youknowone** [comment]
I didn't know `prettifier` also check `.md` and `.html` files

**Comment by PIG208** [comment]
OpenSSL v3.1.1 was [approved](https://community.chocolatey.org/packages/openssl#releasenotes:~:text=Tuesday%2C%20July%2018%2C%202023) on Choco on July 18. It is a major update and likely breaks The [migration guide](https://www.openssl.org/docs/man3.1/man7/migration_guide.html) might be useful to inform what has been changed. Looks like the breakage happens here: https://github.com/RustPython/RustPython/blob/bdb0c8f64557e0822f0bcfd63defbad54625c17a/stdlib/src/ssl.rs#L627-L686

**Comment by youknowone** [comment]
@PIG208 Thank you! Not sure it was a full fix, but I made fix in #5044

**Pull request merged**
