### PR TITLE
Unskip more macOS tests in CI

### PR DESCRIPTION
**Pull request by fanninpm**
This PR will incrementally determine exactly which tests must be skipped on the macOS CI run. Submitting as draft until everything is narrowed down.

### CODE REVIEW

**Comment by coolreader18** [comment]
Shoot... I probably should've mentioned this earlier but I wasn't entirely sure then, but I think the reason those were skipped is just because the macos runner is a lot slower -- ubuntu/windows take about 20 minutes, while the macos run for the latest commit took 40 minutes. It wasn't actually because they were failing on macos.

**Comment by fanninpm** [comment]
> the macos runner is a lot slower -- ubuntu/windows take about 20 minutes, while the macos run for the latest commit took 40 minutes

If you want, you could defer this PR. To that end, I have noticed that the _build_ times on the macOS runner are about 3-4x slower than those on the Ubuntu or Windows runners. However, I have also noticed that the addition of the extra texts added little to the overall run time.

**Comment by coolreader18** [comment]
Huh, I guess that's true, other PRs have macos taking like 35m. This is \~probably\~ fine then

**Comment by coolreader18** [comment]
Ohhh right, I turned off caching for macos cause it was erroring. Do you want to see if it works now? I think you can just the `if: runner.os != 'macOS'` from the actions/cache step.

**Comment by fanninpm** [comment]
I just found [this action](https://github.com/Swatinem/rust-cache), which claims to work around currently unresolved issues that corrupt the cache on macOS builds. I don't think it would be too hard to implement.

**Comment by fanninpm** [comment]
@coolreader18 should I put that GitHub action in, or should I leave this as it is?

**Comment by coolreader18** [comment]
@fanninpm I think that'd be good

**Review by coolreader18 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
