### PR TITLE
new wasm example: notebook inspired by alpha.iodide.io

### PR DESCRIPTION
**Pull request by mireille-raad**
This PR is for a new example under the `wasm` directory. Inspired by iodide, a Mozilla Project https://alpha.iodide.io/ (now abandoned).

This example re-uses the code from `wasm/demo` and adds a basic import code functionality from `api.github.com`

Here is how it looks like:
Screenshot from 2020-09-14 21-51-25

Here is how the import works:
Screenshot from 2020-09-14 21-53-25

Here are the url for test imports (can be anything public as long as it uses the github api url):
https://api.github.com/repos/RustPython/RustPython/contents/wasm/demo/snippets/asyncbrowser.py
https://api.github.com/repos/RustPython/RustPython/contents/wasm/demo/snippets/fetch.py

Here is how the notebook looks like after fetching
Screenshot from 2020-09-14 21-53-42

Then code execution 
Screenshot from 2020-09-14 22-13-27

Changes:
- Removed xterm
- Changed the output from a text area to an HTML element (so later on, I can toy with adding markdown, graphs or interactive elements). If you print an html tag for example, it renders ;p 
- For faster load time, I disable the default snippet imports and execution
- Added the ability to import public python code from GitHub.
- Removed things in the UI

Submitting a PR and looking for feedback on:
- code
- UI tweaks
- features like should this only import from api.github.com or add others?
- Instead of this, should I try to do a notebook that looks like a Jupyter Lab Notebook instead?

### CODE REVIEW

**Comment by coolreader18** [comment]
Is there a reason it can't just fetch from the raw github url? e.g. https://raw.githubusercontent.com/RustPython/RustPython/master/wasm/demo/snippets/asyncbrowser.py

**Comment by mireille-raad** [comment]
The reason for using the GitHub API is:
- I was thinking we could use some of the github api features/integrations later on
- I could have done some javascript that figures out the github api url from the raw one, but I was a bit lazy. 

Now that I thought of it, it is better to just import raw files from everywhere, the github integration is not worth it or it is just a lock-in.

I updated the code which made it less complicated since there is no Base64 encoding/decoding of the content.

I tested by uploading the same code to a Netlify site:
https://reverent-fermat-2bdba5.netlify.app/test.txt 

The only thing that we need to give heads up about is that CORS configuration needs to be ` Access-Control-Allow-Origin = "*"`

**Comment by coolreader18** [comment]
Do we want this to be at like `rustpython.github.io/demo/notebook`? Then we could upload to the same repo as the other demo, we wouldn't have to set up a new one with new deploy keys

**Comment by coolreader18** [comment]
Oh, and it probably goes without saying, but this looks really great :))

**Comment by mireille-raad** [comment]
Why not. It would be easier/better. And other demos can go there as well.

**Review by coolreader18 — APPROVED** [review]
LGTM; if you want to mess around with the github workflow feel free, otherwise I could merge this and edit it separately

**Comment by mireille-raad** [comment]
If you can merge and edit separately, that would be better.

**Comment by coolreader18** [comment]
Thanks for contributing!

**Comment by youknowone** [comment]
@mireille-raad would you please check gitter messages when possible?

**Comment by youknowone** [comment]
> Instead of this, should I try to do a notebook that looks like a Jupyter Lab Notebook instead?

I think both iodide and jupyter notebook style is useful. But which one will be more useful (or more impressive) for now? We must consider we now have limited features of python.

**Pull request merged**
