### PR TITLE
WIP: Added default __and__

### PR DESCRIPTION
**Pull request by BojanKogoj**
For all objects without defined __and__ this should be a default error

### CODE REVIEW

**Comment by cthulahoops** [comment]
I don't think object should have an __and__. 
```
>>> dir(object)
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
```

I think, that for ```a & b``` we need to:

1. Call ```a.__and__(b)``` if defined.
2. Call ```b.__rand__(a)``` if defined.
3. Otherwise raise a TypeError.

**Comment by BojanKogoj** [comment]
Right now if object has `__and__` implementation it will call it (for example objint), otherwise throws TypeError.
What you are suggesting is not to implement default `__and__` at all? That means I would have to check if `__and__` and `__rand__` exist some other way, not sure how

**Comment by windelbouwman** [comment]
You can use `obj.has_attr("__and__")` and modify the `_and` function in `vm.rs`.

**Comment by windelbouwman** [comment]
I added the discussed logic in for substraction: https://github.com/RustPython/RustPython/blob/master/vm/src/vm.rs#L380

**Pull request merged**
