### PR TITLE
DX improvements: Updated MSRV, added cargo deny toml file, and added lints to workspace

### PR DESCRIPTION
**Pull request by JamesClarke7283**
This PR, updates the following:
- MSRV for rustpython
- Adds deny.toml to allow better auditing of project.
- Adds lints to workspace Cargo.toml and inherit to their members.
- Use system ffi library for jit crate to fix build issue on some systems.

### CODE REVIEW

**Comment by youknowone** [comment]
you seem to forgot to set git user.email field

**Comment by JamesClarke7283** [comment]
> you seem to forgot to set git user.email field or unmatching email address not listed in github settings

I fixed it by adding the email to my account, but for some reason its not changed yet.

**Comment by JamesClarke7283** [comment]
Clippy is more pedantic now is why its failing, I will work on this issue tomorrow.

**Comment by JamesClarke7283** [comment]
@youknowone Ready to merge.

**Review by youknowone — APPROVED** [review]
Thank you!

**Pull request merged**
