### PR TITLE
increase stack size for windows

### LINKED ISSUE #2881: cargo run with Debug mode generates STACK_OVERFLOW error
My laptop's OS is Window 10 home with Intel 64 bit CPU.

In terminal if I run `cargo run -- Lib/test/test_math.py` which is **Debug** mode, it generate STACK_OVERFLOW error with these lines:

PS C:\Users\HyunwooJo\Desktop\RustPython> cargo run -- Lib/test/test_math.py
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.86s
    Running `target\debug\rustpython.exe Lib/test/test_math.py

thread 'main' has overflowed its stack
error: process didn't exit successfully: target\debug\rustpython.exe Lib/test/test_math.py (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)
```

However, if I run with **Release** mode, it runs well like this :

PS C:\Users\HyunwooJo\Desktop\RustPython> cargo run --release Lib/test/test_math.py
```
    Finished release [optimized] target(s) in 0.95s
     Running `target\release\rustpython.exe Lib/test/test_math.py
WARNING: The filename '@test_45980_tmp-σà▒┼üΓÖí═ú∩┐╜' CAN be encoded by the filesystem encoding (utf-8). Unicode filename tests may not be effective
testAcos (__main__.MathTests) ... ok
testAcosh (__main__.MathTests) ... ok
testAsin (__main__.MathTests) ... ok
testAsinh (__main__.MathTests) ... ok
testAtan (__main__.MathTests) ... ok
testAtan2 (__main__.MathTests) ... ok
testAtanh (__main__.MathTests) ... expected failure
testCeil (__main__.MathTests) ... ok
testComb (__main__.MathTests) ... ok
testConstants (__main__.MathTests) ... ok
testCopysign (__main__.MathTests) ... ok
testCos (__main__.MathTests) ... ok
testCosh (__main__.MathTests) ... ok
testDegrees (__main__.MathTests) ... ok
testDist (__main__.MathTests) ... expected failure
testExp (__main__.MathTests) ... ok
testFabs (__main__.MathTests) ... ok
testFactorial (__main__.MathTests) ... ok
testFactorialHugeInputs (__main__.MathTests) ... skipped 'implementation detail specific to cpython'
testFactorialNonIntegers (__main__.MathTests) ... expected failure
testFloor (__main__.MathTests) ... ok
testFmod (__main__.MathTests) ... ok
testFrexp (__main__.MathTests) ... ok
testFsum (__main__.MathTests) ... ok
testGcd (__main__.MathTests) ... ok
testHypot (__main__.MathTests) ... ok
testIsfinite (__main__.MathTests) ... ok
testIsinf (__main__.MathTests) ... ok
testIsnan (__main__.MathTests) ... ok
testIsqrt (__main__.MathTests) ... ok
testLdexp (__main__.MathTests) ... ok
testLog (__main__.MathTests) ... expected failure
testLog10 (__main__.MathTests) ... expected failure
testLog1p (__main__.MathTests) ... expected failure
testLog2 (__main__.MathTests) ... expected failure
testLog2Exact (__main__.MathTests) ... ok
testModf (__main__.MathTests) ... ok
testPerm (__main__.MathTests) ... ok
testPow (__main__.MathTests) ... expected failure
testRadians (__main__.MathTests) ... ok
testRemainder (__main__.MathTests) ... expected failure
testSin (__main__.MathTests) ... ok
testSinh (__main__.MathTests) ... ok
testSqrt (__main__.MathTests) ... ok
testTan (__main__.MathTests) ... ok
testTanh (__main__.MathTests) ... ok
testTanhSign (__main__.MathTests) ... ok
test_exceptions (__main__.MathTests) ... ok
test_inf_constant (__main__.MathTests) ... ok
test_issue39871 (__main__.MathTests) ... ok
test_mtestfile (__main__.MathTests) ... ok
test_nan_constant (__main__.MathTests) ... ok
test_nextafter (__main__.MathTests) ... ok
test_prod (__main__.MathTests) ... expected failure
test_testfile (__main__.MathTests) ... expected failure
test_trunc (__main__.MathTests) ... ok
test_ulp (__main__.MathTests) ... ok
testlcm (__main__.MathTests) ... ok
test_asymmetry (__main__.IsCloseTests) ... ok
test_decimals (__main__.IsCloseTests) ... ok
test_eight_decimal_places (__main__.IsCloseTests) ... ok
test_fractions (__main__.IsCloseTests) ... ok
test_identical (__main__.IsCloseTests) ... ok
test_identical_infinite (__main__.IsCloseTests) ... ok
test_inf_ninf_nan (__main__.IsCloseTests) ... ok
test_integers (__main__.IsCloseTests) ... ok
test_near_zero (__main__.IsCloseTests) ... ok
test_negative_tolerances (__main__.IsCloseTests) ... ok
test_zero_tolerance (__main__.IsCloseTests) ... ok
Ran 69 tests in 34.351s`
```

----------------------------------------------------------------------

### PR DESCRIPTION
**Pull request by youknowone**
fix #2881

could anyone using windows test if this change works?

### CODE REVIEW

**Comment by oroppas** [comment]
On my window 10,

```
C:\msys64\home\ryuta\packages\rustpython\rustpython>cargo run --release --features ssl
warning: C:\msys64\home\ryuta\packages\rustpython\rustpython\Cargo.toml: unused manifest key: target.cfg(target_os = "windows").build
...
```

**Comment by youknowone** [comment]
Thank you for testing. I'd better to try it later when I have a windows machine.

**Comment by youknowone** [comment]
@oroppas I changed it only applied to msvc. I think msys64 needs different option. Will you try to build it with `-C link-args=-Wl,-zstack-size=8000000` and see if it is fixed in your environment?

**Comment by oroppas** [comment]
@youknowone 

I tried on msys64

```@@ -45,6 +45,8 @@ flamescope = { version = "0.1", optional = true }
 [target.'cfg(not(target_os = "wasi"))'.dependencies]
 rustyline = "9"

+[target.'cfg(target_env = "msvc")'.build]
+rustflags = "-C link-args=-Wl,-zstack-size=8000000"

 [target.'cfg(not(target_os = "windows"))'.build-dependencies]
 pre-commit = "0.5.2"
```

```
ryuta@sapporo UCRT64 ~/packages/rustpython/rustpython
$ RUSTPYTHONPATH=`pwd`/Lib cargo run --release --features ssl
warning: C:\msys64\home\ryuta\packages\rustpython\rustpython\Cargo.toml: unused manifest key: target.cfg(target_env = "msvc").build
   Compiling rustpython v0.1.2 (C:\msys64\home\ryuta\packages\rustpython\rustpython)
    Finished release [optimized] target(s) in 8.61s
     Running `target\release\rustpython.exe`
Welcome to the magnificent Rust Python 0.1.2 interpreter 😱 🖖

quit()
```

and on msvc

```
@@ -45,6 +45,8 @@ flamescope = { version = "0.1", optional = true }
 [target.'cfg(not(target_os = "wasi"))'.dependencies]
 rustyline = "9"

+[target.'cfg(target_env = "msvc")'.build]
+rustflags = "-C link-arg=/STACK:8000000"

 [target.'cfg(not(target_os = "windows"))'.build-dependencies]
 pre-commit = "0.5.2"
```

```
C:\Users\ryuta\packages\rustpython\rustpython>cargo run --release --features ssl
warning: C:\Users\ryuta\packages\rustpython\rustpython\Cargo.toml: unused manifest key: target.cfg(target_env = "msvc").build
   Compiling rustpython v0.1.2 (C:\Users\ryuta\packages\rustpython\rustpython)
    Finished release [optimized] target(s) in 6.20s
     Running `target\release\rustpython.exe`
Welcome to the magnificent Rust Python 0.1.2 interpreter 😱 🖖
>>>>> quit()
```

**Comment by youknowone** [comment]
@oroppas thank you for testing! I think msys64 test failed because cfg condition is not properly set. I updated `Cargo.toml` file for both cases.

In local, you can test it without editing `Cargo.toml` but passing environment variable like:
```sh
RUSTFLAGS="-C link-args=-Wl,-zstack-size=8000000" cargo run
```

**Comment by DimitrisJim** [comment]
I feel like there might be more issues that are closed by this. I can't test this, is this okay to merge?

**Comment by oroppas** [comment]
I'm seeing

```
warning: unused key `build` in [target] config table `cfg(all(target_os = "windows", not(target_env = "msvc")))`
warning: unused key `build` in [target] config table `cfg(target_env = "msvc")`
```

on both msvc and msys64. Is this expected?

**Comment by youknowone** [comment]
@oroppas I removed `build` key from last commit https://github.com/youknowone/RustPython/pull/3082/commits/e62e61f2ad994dd8d9bca4964467d5d770f00a6b

**Comment by oroppas** [comment]
@youknowone

It turned out,  on msys64, `-zstack-size` is unrecognized

```
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: unrecognized option '-zstack-size=8000000'
```

I had to change it to

```
[target.'cfg(all(target_os = "windows", not(target_env = "msvc")))']
rustflags = "-C link-args=-Wl,--stack,8000000"
```

to make it work.

**Comment by youknowone** [comment]
@oroppas Thanks! I updated it

**Comment by youknowone** [comment]
@oroppas could you check the changed cargo.toml file work please?

@DimitrisJim @coolreader18 would this be ok? should it be adapted only for debug build?

**Comment by oroppas** [comment]
@youknowone I can confirm `.cargo/config.toml` with

```
[target.'cfg(target_env = "msvc")']
rustflags = "-C link-arg=/STACK:8000000"

[target.'cfg(all(target_os = "windows", not(target_env = "msvc")))']
rustflags = "-C link-args=-Wl,--stack,8000000"
```

works on both `msvc` (with `cl` version `19.30.30528` for `x64`) and `MINGW64_NT-10.0-18363 3.2.0-340.x86_64` (i.e., `msys64`).

**Comment by youknowone** [comment]
@oroppas  Thanks a lot.

Because this is too much painful for windows users, let's go for it now and fix any problem later

**Comment by oroppas** [comment]
@youknowone `.cargo/config.toml` for `msys64` still looks like

```
[target.'cfg(all(target_os = "windows", not(target_env = "msvc")))']
rustflags = "-C link-args=-Wl,-zstack-size=8000000"
```

The correct one is

```
[target.'cfg(all(target_os = "windows", not(target_env = "msvc")))']
rustflags = "-C link-args=-Wl,--stack,8000000"
```

**Comment by youknowone** [comment]
oops, changed msvc one not the other one.

**Pull request merged**
