### PR TITLE
property type: Added __doc__

### PR DESCRIPTION
**Pull request by ZapAnton**

### CODE REVIEW

**Comment by veera83372** [comment]
Sorry I did not see this before but I have added test, would you consider that to be there for merging?

**Comment by ZapAnton** [comment]
I thought @windelbouwman preferred that there would be no tests as per [this comment](https://github.com/RustPython/RustPython/pull/327#issuecomment-461577440)?

**Comment by veera83372** [comment]
Okay I have not seen that commit and now I have closed mine

**Comment by windelbouwman** [comment]
@ZapAnton No tests are needed in my opinion for the doc strings. Also, please feel free to combine several doc strings in a single pull request.

**Pull request merged**
