### PR TITLE
Update traceback

### PR DESCRIPTION
**Pull request by youknowone**

### CODE REVIEW

**Comment by youknowone** [comment]
dependency of #3862

**Review by fanninpm — APPROVED** [review]

**Comment by fanninpm** [comment]
I think we should wait for CI to finish before merging.

___

On a tangential note, do you want to add [Bors](https://github.com/bors-ng/bors-ng) to this repository?

**Comment by youknowone** [comment]
huh... the result of running `cargo run Lib/test/test_traceback.py` and `cargo run -- -m test test_traceback` are different.

**Comment by fanninpm** [comment]
> huh... the result of running `cargo run Lib/test/test_traceback.py` and `cargo run -- -m test test_traceback` are different.

Hence why I made #3807.

**Comment by youknowone** [comment]
I though both of running should pass. Does former one also fail in CPython?

**Pull request merged**
