### PR TITLE
Implement Tok::Comment

### PR DESCRIPTION
**Pull request by charliermarsh**
Resolves: #4265.

### CODE REVIEW

**Comment by charliermarsh** [comment]
(Fixing tests.)

**Review by youknowone — DISMISSED** [review]

**Comment by charliermarsh** [comment]
There's something I don't understand in the parsing / compilation flow that's causing this to error. Need to spend a bit more time digging into it.

**Comment by charliermarsh** [comment]
Good to go from my perspective.

**Review by DimitrisJim — APPROVED** [review]
lgtm too, no idea why the runner for mac hanged for a previous run there.

**Pull request merged**
