### PR TITLE
Add comment to create empty PR

### PR DESCRIPTION
**Pull request by doc-jones**
I was told in chat to create an empty PR to claim an issue or feature to contribute. If there is a different preferred process please advise.

### CODE REVIEW

**Comment by Pluriscient** [comment]
Any progress on this @doc-jones ?

**Comment by doc-jones** [comment]
> Any progress on this @doc-jones ?

You are the 1st person to respond.  So, no progress so far.  Can you help?

**Comment by Pluriscient** [comment]
What's the blocker?

**Comment by coolreader18** [comment]
Oh, sorry I missed this @doc-jones. Yeah, I think it would be good to reference #1175 in the comment, so people know what's available to work on. Also, I'm not sure what you mean by empty PR, I think generally just commenting in the issue is enough to mark that you're working on a given `os` function.

**Comment by DimitrisJim** [comment]
Hey @doc-jones , I'm closing this. As coolreader18 mentioned, you can go at the issue and comment there what method you're working on for others to see.

**Pull request closed without merging**
