### PR TITLE
Incrementally adding OpenBSD support (pt. 1)

### PR DESCRIPTION
**Pull request by CodeTriangle**
In #1945, I mentioned some suggestions to improve support for OpenBSD. These are a bunch of minor changes, mostly adding some `#[cfg(target_os = "openbsd")]`.  Check out #1945 for more discussion, and stay tuned for more OpenBSD-related Pull Requests in the future.

### CODE REVIEW

**Comment by coolreader18** [comment]
Looks like rustfmt isn't happy; try running `cargo fmt` in the rustpython directory and it should fix it.

**Comment by CodeTriangle** [comment]
Premature push, sorry.

**Comment by CodeTriangle** [comment]
Hmm, looks like the macos rust tests are failing. Do you know why this is? The interface doesn't really have much information.

**Comment by coolreader18** [comment]
It might've been something weird with push timing cancelling an old one; I'll rerun it.

**Comment by coolreader18** [comment]
Actually, it should fix itself if I just merge to master; it'll rerun CI then. Thanks so much for contributing!

**Pull request merged**
