### PR TITLE
revise PySuper::getattro same as CPython super_getattro

### PR DESCRIPTION
**Pull request by youknowone**
possibly related to #3057 but didn't solve the problem itself

### CODE REVIEW

**Comment by youknowone** [comment]
@eldpswp99 could you review this PR? I think you also reviewed cpython super_getattro

**Review by eldpswp99 — APPROVED** [review]
LGTM! I think this revision follows CPython more than before.

**Comment by fanninpm** [comment]
Does this affect the results of `test_pysuper.py`?

**Comment by youknowone** [comment]
rebased it onto test_super.py but nothing changed.

**Review by DimitrisJim — APPROVED** [review]
making the names follow the ones used in CPython made this easy to review. p.s the soundforge bug report (SF ID #743627) is actually a dead-end, probably a relic left over in the CPython code.

**Comment by youknowone** [comment]
I replaced it to alive link

**Pull request merged**
