### PR TITLE
Refactor symbolic strings

### LINKED ISSUE #463: Refactor Symbolic Strings
There are symbolic strings littered throughout the code base.
e.g. "\_\_repr\_\_", "\<module\>"

These should be hidden behind ~enums~ static constants

### PR DESCRIPTION
**Pull request by ZapAnton**
This PR replaces the occurrences of the symbolic strings like `"__repr__"` with the appropriate static string.

Closes #463

### CODE REVIEW

**Comment by OddCoincidence** [comment]
Hmm, I don't really see the benefits of this. Seems like just using the actual names is more clear...

**Comment by ZapAnton** [comment]
Maybe the naming of the variables could be betters, but I think that having only one variable located in one specific place, instead of manipulating the strings all over the code base, should be more optimal for the future refactoring.

**Comment by OddCoincidence** [comment]
I don't think the usual "put in constant to ease future refactoring" argument makes sense here though - these values will never change.

**Comment by cthulahoops** [comment]
For me this seems to make the code harder to read.

**Comment by ZapAnton** [comment]
I will closing this one then. Should #463 be closed too?

**Pull request closed without merging**
