### PR TITLE
Add sinh and cosh to cmath implementation

### PR DESCRIPTION
**Pull request by emhagman**
This adds the `sinh` and `cosh` methods for complex numbers. Adds two more to https://github.com/RustPython/RustPython/issues/3039

### CODE REVIEW

**Comment by DimitrisJim** [comment]
Seems like you need to rebase to include recent changes (probably #3174 and #3175).

**Review by youknowone — CHANGES_REQUESTED** [review]
Your work looks based on older version of our repository. Could you please rebase your work onto the current main branch?

**Comment by youknowone** [comment]
rebase is always preferred but this patch doesn't need commit history, so squash is also ok. Then please check the test part. Then everything will be perfect!

**Comment by emhagman** [comment]
@youknowone Awesome, sounds good. Will do!

**Comment by youknowone** [comment]
run fmt please (check the failed CI job)

**Comment by emhagman** [comment]
@youknowone Sorry just noticed and ran it

**Review by DimitrisJim — APPROVED** [review]
great, thanks!

**Pull request merged**
