### PR TITLE
Refactor OSError

### PR DESCRIPTION
**Pull request by deantvv**
Implement `raw_os_error_to_exc_type` to reduce duplication of errno to
exception type.

### CODE REVIEW

**Comment by youknowone** [comment]
@ChJR could you review this PR?

**Comment by ChJR** [comment]
I think this PR makes OSError better before.

**Comment by ChJR** [comment]
If this PR can be merged into 'main' branch, it could be helpful for making errno as attribute, required to pass windows test of #2993.

**Review by youknowone — APPROVED** [review]

**Comment by youknowone** [comment]
thank you!

**Pull request merged**
