### PR TITLE
Feature: sys.thread_info

### PR DESCRIPTION
**Pull request by TwoPair**
Implementation - `sys.thread_info` 

close: #4014

### CODE REVIEW

**Comment by youknowone** [comment]
I have no clue how new test_os errors are related with this changes

**Comment by TwoPair** [comment]
```log
======================================================================
[7605](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7606)
FAIL: test_utime_by_indexed (test.test_os.UtimeTests)
[7606](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7607)
----------------------------------------------------------------------
[7607](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7608)
Traceback (most recent call last):
[7608](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7609)
  File "/home/runner/work/RustPython/RustPython/vm/pylib-crate/Lib/test/test_os.py", line 816, in test_utime_by_indexed
[7609](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7610)
    self._test_utime(set_time)
[7610](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7611)
  File "/home/runner/work/RustPython/RustPython/vm/pylib-crate/Lib/test/test_os.py", line 791, in _test_utime
[7611](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7612)
    self.assertEqual(st.st_atime_ns, atime_ns)
[7612](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7613)
  File "/home/runner/work/RustPython/RustPython/vm/pylib-crate/Lib/unittest/case.py", line 845, in assertEqual
[7613](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7614)
    assertion_func(first, second, msg=msg)
[7614](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7615)
  File "/home/runner/work/RustPython/RustPython/vm/pylib-crate/Lib/unittest/case.py", line 838, in _baseAssertEqual
[7615](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7616)
    raise self.failureException(msg)
[7616](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7617)
AssertionError: 1002003001 != 1002003000
[7617](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7618)

[7618](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7619)
======================================================================
[7619](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7620)
FAIL: test_utime_by_times (test.test_os.UtimeTests)
[7620](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7621)
----------------------------------------------------------------------
[7621](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7622)
Traceback (most recent call last):
[7622](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7623)
  File "/home/runner/work/RustPython/RustPython/vm/pylib-crate/Lib/test/test_os.py", line 825, in test_utime_by_times
[7623](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7624)
    self._test_utime(set_time)
[7624](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7625)
  File "/home/runner/work/RustPython/RustPython/vm/pylib-crate/Lib/test/test_os.py", line 791, in _test_utime
[7625](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7626)
    self.assertEqual(st.st_atime_ns, atime_ns)
[7626](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7627)
  File "/home/runner/work/RustPython/RustPython/vm/pylib-crate/Lib/unittest/case.py", line 845, in assertEqual
[7627](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7628)
    assertion_func(first, second, msg=msg)
[7628](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7629)
  File "/home/runner/work/RustPython/RustPython/vm/pylib-crate/Lib/unittest/case.py", line 838, in _baseAssertEqual
[7629](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7630)
    raise self.failureException(msg)
[7630](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7631)
AssertionError: 1002003001 != 1002003000
[7631](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7632)

[7632](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7633)
----------------------------------------------------------------------
[7633](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7634)
Ran 315 tests in 1.765s
[7634](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7635)

[7635](https://github.com/RustPython/RustPython/runs/7790368279?check_suite_focus=true#step:12:7636)
FAILED (failures=2, skipped=108, expected failures=12)
```

Two tests completely unrelated with my pr show the same failed result.
Do you have any idea for this?

**Comment by youknowone** [comment]
that's revealed related to rust compiler version update last night

**Review by youknowone — APPROVED** [review]
Thank you!

**Pull request merged**
