### PR TITLE
[WASM] Make setStdout arguments more explicit in what they print to

### PR DESCRIPTION
**Pull request by coolreader18**
So a string doesn't mean a CSS selector anymore it means a string enum of, for now, just "console", and `undefined` means nothing, and an `HTMLTextAreaElement` is a textarea console to print to.

### CODE REVIEW

**Comment by palaviv** [comment]
You should probably update the documentation in the demo.

**Comment by palaviv** [comment]
This is a great change. I actually needed it at some point when I added the interactive shell :). Why does it have to be a `textarea`?

**Comment by coolreader18** [comment]
That's what we use for the demo, and I think that if you're going to set stdout to an HTML element, it should probably be a textarea due to the way it's displayed. I might add support for other HTML elements just using textContent, though.

**Comment by palaviv** [comment]
> That's what we use for the demo, and I think that if you're going to set stdout to an HTML element, it should probably be a textarea due to the way it's displayed. I might add support for other HTML elements just using textContent, though.

I actually think that we should keep only the function option. The `textarea` is too specific and can be done simply by using a js function.

**Comment by coolreader18** [comment]
Alright, that's sort of vestigial anyway from when the wasm crate was specific to just the demo.

**Comment by coolreader18** [comment]
Oh, and I'll update the docs in a separate PR, cause there's a lot that's changed since they were written.

**Pull request merged**
