### PR TITLE
`id()` for `bytes` stays the same after `* 1`

### PR DESCRIPTION
**Pull request by sobolevn**
Refs #2840

Only `str` is left.

### CODE REVIEW

**Review by DimitrisJim — APPROVED** [review]

**Comment by youknowone** [comment]
I expected those are tested by CPython unittest suites 😕

**Comment by sobolevn** [comment]
@youknowone me too, but I was not able to find any for `bytes`. Maybe it is something to contribute to CPython? 🙂

**Comment by fanninpm** [comment]
The CPython test suites in *this* repository are currently incomplete.

**Comment by youknowone** [comment]
@sobolevn yes, if we can cover tests with CPython one, we don't need to manage our own `extra_tests`. less code means less management cost.

**Comment by sobolevn** [comment]
@fanninpm I was searching in CPython's repo as well: https://github.com/python/cpython/blob/main/Lib/test/test_bytes.py
Do you have any specific CPython's test to point me to? 🤔

**Comment by fanninpm** [comment]
> @fanninpm I was searching in CPython's repo as well: https://github.com/python/cpython/blob/main/Lib/test/test_bytes.py
> Do you have any specific CPython's test to point me to?

After a cursory search, I couldn't find anything specific. I suggest asking the wiser folks on https://bugs.python.org.

**Pull request merged**
