### PR TITLE
update imp.py from CPython 3.11

### PR DESCRIPTION
**Pull request by Reid00**
related: https://github.com/RustPython/RustPython/issues/4564

### CODE REVIEW

**Comment by youknowone** [comment]
This PR  contains previously merged commit about test_hashlib.
You probably want to use `git rebase` or `git reset --hard` to clear the upstream context before making a patch.
Using patch branches rather than main will also be helpful to make those work easier.

**Comment by youknowone** [comment]
Would you check if your git email configuration matches to the github id?

Checking current config:
```
git config user.email
```

You can change either the local config or GitHub config to make them aligned

**Comment by Reid00** [comment]
Thank you for your advice. I changed the local user.email and will use patch branches/

**Review by youknowone — APPROVED** [review]
Thank you for contributing!

**Pull request merged**
