### PR TITLE
Reduce runtime of stdlib_collections_deque

### PR DESCRIPTION
**Pull request by youknowone**

### CODE REVIEW

**Comment by fanninpm** [comment]
Has this been known to slow down the test suite appreciably? In the long term, it might be better to improve our implementation.

**Comment by youknowone** [comment]
I am using pretty good machine but it takes 73 seconds on debug build.

**Comment by youknowone** [comment]
I didn't check what it actually tests. Maybe we don't need it if we have same thing on cpython test suite

**Comment by DimitrisJim** [comment]
there's probably some clean-up that can be done in `extra_tests` for sure.

**Comment by youknowone** [comment]
Agree

**Pull request merged**
