### PR TITLE
Add `math.exp2` implemented in cpython 3.11

### PR DESCRIPTION
**Pull request by jopemachine**
`math.exp2` return 2 raised to the power x.

## Related links

* Python codes are copy-pasted from CPython.

- https://github.com/python/cpython/pull/29829

- [Python documentation](https://docs.python.org/3.11/library/math.html#math.exp2)

### CODE REVIEW

**Comment by youknowone** [comment]
The rust part looks great. Could you also check if you followed this guideline?
https://github.com/RustPython/RustPython/wiki/How-to-update-test-files

**Comment by jopemachine** [comment]
> The rust part looks great. Could you also check if you followed this guideline? [RustPython/RustPython/wiki/How-to-update-test-files](https://github.com/RustPython/RustPython/wiki/How-to-update-test-files)

Thanks for letting me know!
I just made a fixing commit.

I didn't include unrelated diffs with `math.exp2` because maybe including these diffs might be out of this PR's scope.

**Comment by youknowone** [comment]
We usually 'sync' our version to a specific CPython version, instead of updating each function. The bulk update is easy by following the guideline.

**Comment by jopemachine** [comment]
> We usually 'sync' our version to a specific CPython version, instead of updating each function. The bulk update is easy by following the guideline.

Understood. I attached `@unittest.expectedFailure` to the expected failed tests.

This could be fixed by other 2 PRs that I made.

**Review by youknowone — APPROVED** [review]
Great, thank you!

**Pull request merged**
