### PR TITLE
add precommit which runs  clippy & fmt

### PR DESCRIPTION
**Pull request by eldpswp99**
add precommit to RustPython
it runs `cargo clippy` / `cargo fmt --all` /  `git add -u` before commit

by running `cargo clean && cargo build`, it adds git hooks to the project.

### CODE REVIEW

**Review by youknowone — APPROVED** [review]
clippy looks heavy for pre-commit hook, but generally looks good.

@coolreader18 @DimitrisJim how do you think?

**Comment by DimitrisJim** [comment]
I wouldn't really like clippy running on each commit I do (fmt seems fine since its instantaneous). I prefer to run clippy right before I push things and if I'm feeling like I made a relatively big change.

I think it would be perfect if it was optional so people who have a different workflow can opt-out of it but I doubt that's possible.

**Comment by eldpswp99** [comment]
then how about if there is only fmt and git add -u statement?

**Comment by youknowone** [comment]
That sounds better to me too

**Pull request merged**
