### PR TITLE
Fix zlib & Temprorally skip zipimport test

### PR DESCRIPTION
**Pull request by youknowone**

### CODE REVIEW

**Comment by coolreader18** [comment]
Wait... is zlib crashing because there's no `#[pyattr]` on the `#[pyclass]`s?

**Comment by youknowone** [comment]
ah, nope. I missed `name = "Compress"` when I changed it before. I am fixing it

**Comment by youknowone** [comment]
We have more failing tests. idk how many of them are regressions

**Comment by youknowone** [comment]
The regressions came from #2106

**Comment by youknowone** [comment]
Addtional PRs to fix regression: #2137 #2138

**Pull request merged**
