### PR TITLE
Update test float from c python v3.12.7

### PR DESCRIPTION
**Pull request by key262yek**
Update Lib/test/test_float.py to CPython v3.12.7
#5104

### CODE REVIEW

**Comment by cclauss** [comment]
Failing formatting test: Two new `Prettier` releases in the past 12 hours... https://github.com/prettier/prettier/releases

**Comment by key262yek** [comment]
@cclauss   I think the new `Prettier` issue is not related to this PR. Could I rebase the branch after other PR fix formatting errors?

**Comment by cclauss** [comment]
If you know how to fix the `Prettier` issue, please do so here or in a separate PR because they are causing failures in this PR, #5445, and #5447.

**Comment by key262yek** [comment]
I misconfigure rebase and pull. I will re-open in another PR

**Pull request closed without merging**
