### PR TITLE
Merge to release

### PR DESCRIPTION
**Pull request by coolreader18**
Mentioned in RustPython/rustpython.github.io#30

I feel pretty confident in the current state of everything, should we merge?

### CODE REVIEW

**Comment by mireille-raad** [comment]
Wait! Can I submit one last PR to make the notebook responsive and mobile/ipad friendly?
It is probably just some simple css work, I can get it done in < 24 hours. It is not necessary, but nice to have.

**Comment by coolreader18** [comment]
Oh yeah, for sure! There's no rush for this.

**Comment by coolreader18** [comment]
Should we merge this now?

**Comment by youknowone** [comment]
oh, I missed this release. 🎉

**Pull request merged**
