### PR TITLE
PyStrInterned for PyAttributes/Constants

### PR DESCRIPTION
**Pull request by youknowone**
2.5% performance gain for pystone

- first bit of `RefCount` is now used to mark leaked objects
- `identifier!()` macro to refer static identifier
- `PyStrInterned` impl `DictKey`

### CODE REVIEW

**Comment by youknowone** [comment]
Do you mean changing `interned` macro to `PyIdentifier`? This is making sense.
Or something like `_Py_IDENTIFIER` to define them? This is not working because we don't have global variables. (Any clever idea?)

**Comment by youknowone** [comment]
@coolreader18 I am sorry, but I think I wasn't getting what you meant correctly. What do you mean by "to call these identifiers"?

**Comment by coolreader18** [comment]
Oh, just in the names, not like change to be the same functionality as the `_Py_IDENTIFIER`

**Comment by youknowone** [comment]
not easy to solve static type problems

**Comment by youknowone** [comment]
@coolreader18 do you have a good idea?

**Comment by youknowone** [comment]
@coolreader18 does `identifier!` look good? `py_identifier!`?

**Comment by youknowone** [comment]
@coolreader18 done

**Pull request merged**
