### PR TITLE
Refactor `ExecutingFrame`

### PR DESCRIPTION
**Pull request by yt2b**
I added the following functions in `ExecutingFrame`.
* `jump_if`
* `jump_if_or_pop`

### CODE REVIEW

**Comment by yt2b** [comment]
CI has failed in `Run rust tests (ubuntu-latest)`.
I don't know why only this test has failed.

**Comment by fanninpm** [comment]
> CI has failed in `Run rust tests (ubuntu-latest)`.
> I don't know why only this test has failed.

This is related to #4309. I recommend rebasing on a fresh copy of `main`.

**Comment by yt2b** [comment]
@fanninpm 
Thank you for the advice.
CI has passed!

**Review by DimitrisJim — APPROVED** [review]
thanks for the refactor!

**Pull request merged**
