### PR TITLE
Add __index__ operator overriding class support for SequenceIndex

### PR DESCRIPTION
**Pull request by Snowapril**
This revision fix three test cases in [test_index.py](https://github.com/RustPython/RustPython/blob/master/Lib/test/test_index.py)
* `SeqTestCase.test_index`
* `SeqTestCase.test_wrappers`
* `ListTestCase.test_setdelitem`

All these three cases' failures were caused by not supporting classes
that override `__index__` operator when indexing sequence type.

This commit implement almost same routine with PR(#2807) which also did not
support classes that override `__index__` operator in range indexing.

### CODE REVIEW

**Comment by Snowapril** [comment]
@youknowone Below tests make current changes unacceptable. Is it better to fix error message `"{} indices be integers or slices or classes that override __index__ operator, not '{}'"` to `"{} indices must be integers or slices, not {}"`?

##### test_tuple.py
```python
    def test_getitem_error(self):
        t = ()
        msg = "tuple indices must be integers or slices"
        with self.assertRaisesRegex(TypeError, msg):
            t['a']
```

##### list_tests.py
```python
    def test_getitem_error(self):
        a = []
        msg = "list indices must be integers or slices"
        with self.assertRaisesRegex(TypeError, msg):
            a['a']
```

**Comment by youknowone** [comment]
The test check whether the actual message include it instead of exact match.
I think you missed `must` in your error message.

**Comment by Snowapril** [comment]
Ah! Thank you. I missed the actual work of `assertRaiseRegex` method. I sent v2 code of this PR.

**Review by youknowone — APPROVED** [review]
Thank you for contributing!

**Comment by youknowone** [comment]
@Snowapril I attached one more commit to refactor `SequenceIndex::Int` cases

**Pull request merged**
