### PR TITLE
Improved the fix for the continuing problem in the shell

### PR DESCRIPTION
**Pull request by branai**
Improved my fix for #3892

### CODE REVIEW

**Comment by youknowone** [comment]
could you please rebase the commits to remove the merge commit?

when `https://github.com/RustPython/RustPython` is upstream, `git rebase -i upstream/main` will work.

**Comment by branai** [comment]
I added two small changes here to `shell.rs`, one fixes the issues with comments by checking the location of indentation errors, the other is for other errors.

@DimitrisJim I'd like to fix `errors.rs`, but I don't understand how to simplify it like you said. Any help you could give would be much appreciated. :)

**Review by youknowone — APPROVED** [review]
looks good. please check the `use` statement part glitch.

**Comment by youknowone** [comment]
Thank you!

**Pull request merged**
