### PR TITLE
Selenium tests for WASM

### PR DESCRIPTION
**Pull request by palaviv**
Not many tests but this should validate we don't break WASM.
I tried using PhantomJS as mentioned in #530 but it did not work...

### CODE REVIEW

**Comment by adrian17** [comment]
That seems like a bit of an overkill to me. Wouldn't it possible to load wasm and run tests on Node?

**Comment by coolreader18** [comment]
Yes, with wasm-bindgen-test, as I mentioned in #530, you can run tests in Node.

**Comment by windelbouwman** [comment]
This is very cool! @palaviv nice job!

**Comment by adrian17** [comment]
> Yes, with wasm-bindgen-test, as I mentioned in #530, you can run tests in Node.

So, why would we need selenium tests, then?

**Comment by windelbouwman** [comment]
@adrian17 I agree with you that this test is spinning up a lot of different tools, but I think it is a good crosscheck. Can we do the same with wasm-bindgen-test in a lightweigher way, or do we exclude some code when we do that?

**Comment by coolreader18** [comment]
wasm-bindgen-test uses the native rust testing framework, e.g. `#[test]`, so we'd have to design our tests around that. Another concern is that as far as I know, there's no way to get code coverage for rust compiled to WASM, so that sucks.

**Comment by palaviv** [comment]
@adrian17 I am not familiar with `wasm-bindgen-test`. I wanted to push something to validate the WASM is  good in the CI as I almost broke it on a typo in #652. I agree selenium is very complex and if we can do it by using other tools lets do that.

**Pull request merged**
