### PR TITLE
os: update test `PidTests`

### PR DESCRIPTION
**Pull request by deantvv**
Follow up test for #3423

### CODE REVIEW

**Comment by DimitrisJim** [comment]
Is this a partial update to the test file?

**Comment by deantvv** [comment]
> Is this a partial update to the test file?

Yes. I was thinking about updating the whole file but it would change `Lib/test/support/` a lot and inevitably will be quite a large PR. I can do that if you prefer it that way.

This PR add one more passing test to windows but it doesn't add any more passing tests in unix since it requires `os.spawnv`.

**Comment by DimitrisJim** [comment]
> Yes. I was thinking about updating the whole file but it would change Lib/test/support/ a lot and inevitably will be quite a large PR. I can do that if you prefer it that way.

That's generally preferable, if you're willing to update them! (If its too much of a hassle I'll take a stab at it when I find time for it)

**Comment by deantvv** [comment]
Yes, I can update them. I will try to find some time next week for it. 
Closing for now, will open another PR once it is ready.

**Pull request closed without merging**
