### PR TITLE
Fix copysign behavior for NaNs

### PR DESCRIPTION
**Pull request by crazymerlyn**
This allows enabling test_constructor_negative_nans_from_string

### CODE REVIEW

**Comment by crazymerlyn** [comment]
The failure in test_re seems independent of the pr as it is also failing on main.

**Comment by youknowone** [comment]
Thank you for checking!

**Comment by youknowone** [comment]
#5398 fixed test_re failure. Could you please rebase it?

**Comment by crazymerlyn** [comment]
Done

**Review by youknowone — APPROVED** [review]
Thank you for contributing and the good catch!

**Pull request merged**
