### PR TITLE
Add `get_int_max_str_digits` and `set_int_max_str_digits` in `sys`.

### PR DESCRIPTION
**Pull request by dannasman**
Hi!

Here is a solution proposal for issue #5010.

### CODE REVIEW

**Comment by youknowone** [comment]
@DimitrisJim do you know if it has related tests?

**Comment by DimitrisJim** [comment]
oh it definitely did. shame I didn't remember mentioning that in the issue, I'll look into it. What on earth is going on with this Mac runner though :face_exhaling:

**Comment by youknowone** [comment]
Don't worry about CI failure. I fixed it here https://github.com/RustPython/RustPython/pull/5012/files#diff-575a2149c1bf435cd04009918dec66fd8fa2be92cf7d5fdcdb48ceb61d3ad4aaR11

**Comment by DimitrisJim** [comment]
Thanks for this @dannasman. These are currently tested indirectly in `test_cmd_line` (this is basically an implementation `-X` flag that can be passed when invoking Python and we don't currently have that part implemented iirc so tests fail).

Could you by any chance add an additional test in `extra_tests/snippets/stdlib_sys.py` that plays with these `get/set` functions on a basic level? Something along the lines of get its value, make sure it equals the default, set it to a bad value, error is raised

**Comment by dannasman** [comment]
Sure :+1:

**Comment by dannasman** [comment]
I am having trouble running `pytest -v` with RustPython instead of my default CPython that I have installed. Do you have any tips on how to run pytest with RustPython?

Also, Is this the correct way of testing whether `set_int_max_str_digits` raises the correct error (`ValueError`)?
```python
with assert_raises(ValueError):
    sys.set_int_max_str_digits(1)
```

**Comment by DimitrisJim** [comment]
Hey, so yeah if you run it with `pytest -v` you should be fine, it calls the RustPython binary itself (see `test_snippets.py`). Pushing directly here is also an option.

> Also, is this the correct way of testing whether set_int_max_str_digits raises the correct error (ValueError)?

Yup! That looks right to me.

**Comment by DimitrisJim** [comment]
Jesus Christ Mac started using `3.11.4` now. I'll push a commit here if you dont mind @dannasman, the runners using different version of Python to run the snippets has been a pain, sorry for the back and forth.

**Comment by dannasman** [comment]
No problem!

**Review by DimitrisJim — APPROVED** [review]
thanks so much @dannasman, lgtm

**Pull request merged**
