### PR TITLE
Fix bug in Sliceable and rename del_item* to delitem

### PR DESCRIPTION
**Pull request by qingshi163**

### CODE REVIEW

**Comment by fanninpm** [comment]
Rust 1.66 was released yesterday, which might explain a few of the CI failures here.

**Comment by fanninpm** [comment]
I merged #4334 an hour ago, so feel free to rebase this branch on a fresh copy of `main`.

**Review by youknowone — APPROVED** [review]
which bug does it fix? is there a related test case?

**Comment by qingshi163** [comment]
> which bug does it fix? is there a related test case?

It was logic bug that always fallback if step == -1

**Pull request merged**
