### PR TITLE
Methods

### PR DESCRIPTION
**Pull request by cthulahoops**

### CODE REVIEW

**Comment by OddBloke** [comment]
Not sure why Travis isn't displaying the diff, but the rustfmt job is failing because:

```
Diff in /home/daniel/personal_dev/RustPython/vm/src/vm.rs at line 638:
                         PyObjectKind::Integer { value } => Some(value),
                         PyObjectKind::None => None,
                         _ => panic!("Expect Int or None as BUILD_SLICE arguments, got {:?}", x),
-                    })
-                    .collect();
+                    }).collect();
 
                 let start = out[0];
                 let stop = out[1];
```

**Comment by OddBloke** [comment]
Oh, it is showing it; not sure how I missed that when I looked the first time around. :-/

**Comment by cthulahoops** [comment]
Seems like my rust-fmt isn't consistent with travis's. (stable vs nightly perhaps?)

**Comment by cthulahoops** [comment]
Updating to nightly looks like it should solve the problem.

**Pull request merged**
