### PR TITLE
Impl PySequence Protocol

### PR DESCRIPTION
**Pull request by qingshi163**
#3244

### CODE REVIEW

**Comment by DimitrisJim** [comment]
Mentioning here so it isn't forgotten, `ItemProtocol` for `PyObjectRef` should be amended to also try the sequence protocol after the mapping one (and before trying to grab `__getitem__`).

**Comment by youknowone** [comment]
I want to request @Snowapril 's review later. He must have been reviewed those mapping/sequence details when he implemented `PyMapping`

**Comment by DimitrisJim** [comment]
sounds good to me

**Comment by qingshi163** [comment]
@youknowone will you review this pr?

**Comment by Snowapril** [comment]
@qingshi163 Hello. Could I ask you is there any progress here?
Does only reviewing required for more progress?

**Comment by youknowone** [comment]
I am sorry, I wasn't aware of pending reveiw request

**Review by youknowone — APPROVED** [review]

**Comment by youknowone** [comment]
@qingshi163 I rebased it to merge, sorry for late review

**Pull request merged**
