### PR TITLE
`threading` support via dummy implementation

### PR DESCRIPTION
**Pull request by alanjds**
`_rp_thread.py` populates `_thread` missing attributes with `_dummy_thread` implementations. This allows `threading.py`  from CPython to be imported.

Copied from CPython:
- `_threading_local.py`: Verbatim
- `threading.py`: One line change `import _rp_thread`

It needs `sys.stdout` to work, so may be needed to merge #1514 before testing this one.

### CODE REVIEW

**Comment by coolreader18** [comment]
#1514 is merged, is this ready for review now?

**Comment by alanjds** [comment]
Well, I made up to the point it imports. I wanted to test it before taking of from draft,  at least manually.

**Comment by alanjds** [comment]
Does not blocks you from taking a look at it :)
Blocks only the merge action.

**Comment by coolreader18** [comment]
Well I think this looks good; I can merge it whenever you're ready.

**Comment by alanjds** [comment]
@coolreader18 I tested locally with simple snippets and is working par with dummy_threading expectations. You can review/merge when ready

**Pull request merged**
