### PR TITLE
Fix `ExprKind::BoolOp` location

### LINKED ISSUE #4305: Is the start location of `ExprKind::BoolOp` correct?
In https://github.com/charliermarsh/ruff/pull/1009, I found the start location of `ExprKind::BoolOp` points to `or` or `and`.

Example:

```python
foo or bar
    ^

foo and bar
    ^

# ^ represents the start location of this BoolOp expression
```

Is this intended? Should the start location point to `foo` in the example above?

```python
foo or bar
^

foo and bar
^
```

### PR DESCRIPTION
**Pull request by harupy**
Fix #4305.

### CODE REVIEW

**Comment by harupy** [comment]
Should I add tests?

```
diff --git a/compiler/parser/src/parser.rs b/compiler/parser/src/parser.rs
index d0f71fc80..f120dae70 100644
--- a/compiler/parser/src/parser.rs
+++ b/compiler/parser/src/parser.rs
@@ -218,4 +218,18 @@ class Foo(A, B):
         let parse_ast = parse_expression(&source, "<test>").unwrap();
         insta::assert_debug_snapshot!(parse_ast);
     }
+
+    #[test]
+    fn test_parse_boolop_or() {
+        let source = String::from("x or y");
+        let parse_ast = parse_expression(&source, "<test>").unwrap();
+        insta::assert_debug_snapshot!(parse_ast);
+    }
+
+    #[test]
+    fn test_parse_boolop_and() {
+        let source = String::from("x and y");
+        let parse_ast = parse_expression(&source, "<test>").unwrap();
+        insta::assert_debug_snapshot!(parse_ast);
+    }
 }
```

**Comment by DimitrisJim** [comment]
Thanks! `test_boolop` in `EndPositionTests` is passing (file `test_ast.py`). Remove the decorator on it to get the stdlib tests to pass again.

**Comment by harupy** [comment]
@DimitrisJim Removed!

**Comment by harupy** [comment]
@DimitrisJim Is the `
CI / Run rust tests (ubuntu-latest) (pull_request)` failure related to this PR?

**Review by DimitrisJim — APPROVED** [review]
failure is unrelated. looks good to me, thanks again!

**Comment by harupy** [comment]
cc @charliermarsh

**Comment by charliermarsh** [comment]
Rad, thanks @harupy!

**Pull request merged**
