### PR TITLE
Update test_string.py

### PR DESCRIPTION
**Pull request by waroad**
Location of errors have changed

### CODE REVIEW

**Review by youknowone — CHANGES_REQUESTED** [review]
The code changes look great. But `string.py` looks like to be updated from CPython 3.8.3 but `test_string.py` is not - it looks 3.8.3 test file but it was already from the version but not updated by this commit. Could you reword your commit message for `test_string.py` to not to mention CPython 3.8.3?

**Comment by waroad** [comment]
> The code changes look great. But `string.py` looks like to be updated from CPython 3.8.3 but `test_string.py` is not - it seems it is the 3.8.3 test file but it was already from the version but not updated by this commit. Could you reword your commit message for `test_string.py` to not to mention CPython 3.8.3?

+Edited as requested

**Comment by youknowone** [comment]
#3453 is just merged - which resolves new errors. Could you rebase this PR once again without new expectedFailure decorators?

**Review by youknowone — APPROVED** [review]

**Comment by youknowone** [comment]
@waroad thank you for contributing

**Pull request merged**
