### PR TITLE
turn on --installp-pip test

### LINKED ISSUE #3670: issue with rustpython --install-pip
on ubuntu 20.04

i am getting this 

######

  File "/home/user/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/4c39668/vm/pylib-crate/Lib/zipimport.py", line 259, in load_module
    exec(code, mod.__dict__)
  File "/tmp/tmp_1qijfve/pip.zip/pip/_vendor/cachecontrol/filewrapper.py", line 6, in <module>
ModuleNotFoundError: No module named 'mmap'

#####

while running

rustpython --install-pip

### PR DESCRIPTION
**Pull request by youknowone**
close #3670

### CODE REVIEW

**Comment by youknowone** [comment]
hmm, what's left?

**Comment by youknowone** [comment]
rebase is not helpful

**Comment by dieterplex** [comment]
Dig into get-pip.py and found that html parser not works. no links could be parsed from the page https://pypi.org/simple/pip/
I guess we should check `html.parser.HTMLParser` first.

Test with
```
> target/release/rustpython get-pip-zip-extracted/__main__.py -vvv install --upgrade --force-reinstall -t site-packages/  pip
```
specific source at `line 353: parser.feed(page.content.decode(encoding))` from `get-pip-zip-extracted/_internal/index/collector.py:parse_links()`.
There is no item in parser.anchor after feed.

**Comment by youknowone** [comment]
Thank you!

**Comment by youknowone** [comment]
try again

**Pull request merged**
