### PR TITLE
Fix multiline lexer bug

### PR DESCRIPTION
**Pull request by kth496**
Fix https://github.com/RustPython/RustPython/issues/3760

### CODE REVIEW

**Comment by Snowapril** [comment]
Looks good! It seems not working for multi-line strings. Could you resolve it in this PR? If it takes long, separating PR is also good.
```python
>>>>> a = [
..... 1,2,3
..... ]
.....
>>>>> a
[1, 2, 3]
>>>>> a = {
..... 1,2,3
..... }
.....
>>>>> a
{1, 2, 3}
>>>>> a = {
..... 1:2,
..... 3:4
..... }
.....
>>>>> a
{1: 2, 3: 4}
>>>>> a = """
SyntaxError: Got unexpected string at line 2 column 2

 ^
```

**Review by youknowone — APPROVED** [review]
nice catch! thank you!

**Comment by youknowone** [comment]
@Snowapril you mean the referred bug is not fixed yet, right?

**Comment by Snowapril** [comment]
Yeah correct ☺️

**Comment by kth496** [comment]
@youknowone @Snowapril Exactly. Only nesting error fixed. I will submit next patch soon :) Thank you for feedbacks!

**Pull request merged**
