### PR TITLE
Fix abc error messages

### LINKED ISSUE #5137: Mismatching abstractmethod error messages
Python 3.12 changed error messages.

https://github.com/RustPython/RustPython/pull/5134/files#diff-e020d5ddd536ec48b0414753af7d5240750a05262f32dad378b4c79e6cc3743dR152-R160 (#5134)

Related source code in RustPython is in `vm/src/builtins/object.rs`.

### PR DESCRIPTION
**Pull request by NakanoMiku39**
Fix #5137

### CODE REVIEW

**Comment by youknowone** [comment]
oh, `test_dataclasses` seems to be related the message changes too

**Comment by NakanoMiku39** [comment]
> oh, `test_dataclasses` seems to be related the message changes too

The test_dataclasses is now a test folder instead of a single test file, and in what way should it be updated?

**Comment by youknowone** [comment]
We have 2 choices.
1. Update test_dataclasses first and finish this PR later. The existing single file will be replaced by folder with this patch.
2. Mark `@unittest.expectedFalure` to current dataclasses test. Then they will be fixed when we update the test later.

**Comment by NakanoMiku39** [comment]
> We have 2 choices.
> 
> 1. Update test_dataclasses first and finish this PR later. The existing single file will be replaced by folder with this patch.
> 2. Mark `@unittest.expectedFalure` to current dataclasses test. Then they will be fixed when we update the test later.

The test files in the folder seems to be unrelated with the test_dataclasses.py though

**Comment by youknowone** [comment]
I checked cpython repository. `test_dataclasses.py` looks still a file in Python 3.12. https://github.com/python/cpython/blob/v3.12.0/Lib/test/test_dataclasses.py
Could you share what's the folder?

**Comment by NakanoMiku39** [comment]
> I checked cpython repository. `test_dataclasses.py` looks still a file in Python 3.12. https://github.com/python/cpython/blob/v3.12.0/Lib/test/test_dataclasses.py Could you share what's the folder?

Oh I was checking out the 3.12 branch [https://github.com/python/cpython/tree/3.12/Lib/test/test_dataclasses](url)

**Comment by youknowone** [comment]
Got it. I think the test is moved to https://github.com/python/cpython/blob/3.12/Lib/test/test_dataclasses/__init__.py

If you run test through `-m test`, both file and folder will work in same way.
`cargo run  -- -m test test_dataclasses`

**Comment by NakanoMiku39** [comment]
> Got it. I think the test is moved to https://github.com/python/cpython/blob/3.12/Lib/test/test_dataclasses/__init__.py
> 
> If you run test through `-m test`, both file and folder will work in same way. `cargo run -- -m test test_dataclasses`

Oh, but we are still following the main branch right? Then I will update the test file and ignore the folder

**Comment by youknowone** [comment]
I prefer to follow recent distribution's tag. I'd like recommend v3.12.1 tag at this time. https://github.com/python/cpython/tree/v3.12.1

**Comment by NakanoMiku39** [comment]
> I prefer to follow recent distribution's tag. I'd like recommend v3.12.1 tag at this time. https://github.com/python/cpython/tree/v3.12.1

I found that test_dataclasses needs support from dataclasses.py, which the latter would went into the `match` statement support issue

**Comment by youknowone** [comment]
Marking test_dataclasses expectedFailure seems reasonable in that case.

**Comment by NakanoMiku39** [comment]
> Marking test_dataclasses expectedFailure seems reasonable in that case.

No it's not working. Things get worse when comment out the parts cuz it is not in a test function
image
image

**Comment by youknowone** [comment]
> Marking test_dataclasses expectedFailure seems reasonable in that case.

I made this temporary change here: https://github.com/RustPython/RustPython/pull/5140/files#diff-f0436842533448f8f02a19081d7c9cc8372b6685756caf32c83dfecebbee68e7R3679

**Review by youknowone — APPROVED** [review]
Thank you!

**Pull request merged**
