### PR TITLE
Add `_statistics` module containing `_normal_dist_inv_cd`

### LINKED ISSUE #3251: Add `_statistics` module containing `_normal_dist_inv_cdf`
This should be _relatively_ easy. `_statistics` needs to be defined as a built-in module and `_normal_dist_inv_cdf` should be added as its sole function.

`_normal_dist_inv_cdf` is pretty straight-forward to implement with the [C version](https://github.com/python/cpython/blob/main/Modules/_statisticsmodule.c#L29) being a pretty direct translation from the [Python version](https://github.com/RustPython/RustPython/blob/main/Lib/statistics.py#L825).

### PR DESCRIPTION
**Pull request by aDotInTheVoid**
Closes #3251

Not sure if this needs a test, or if you run the python ones in `Lib/test/test_statistics.py` is enough

### CODE REVIEW

**Comment by aDotInTheVoid** [comment]
> In addition to that, no need to define function outside and then use super here.

I thing this is good as one function handles the stats, and the other handles the arg conversion and error.

The tests now pass

**Comment by youknowone** [comment]
@DimitrisJim how this one has going? is this need to be rebased?

**Comment by fanninpm** [comment]
Sorry, I forgot that this PR existed when I trampled on it with #3552.

**Comment by youknowone** [comment]
This version is better structured than current version. I rebased this version on the main branch.

**Comment by youknowone** [comment]
@aDotInTheVoid I am sorry for making you wait for this for so long time. I didn't know this is untracked.

**Pull request merged**
