### PR TITLE
Refactor function signatures

### PR DESCRIPTION
**Pull request by youknowone**
- Result<T, PyObjectRef> -> PyResult<T>
- Make pymethod return types as small as possible

### CODE REVIEW

**Comment by windelbouwman** [comment]
Wow, this is really nice, but also a lot of code. Did you do this manually or automated? Would it be possible to split this work into several pull requests?

**Comment by youknowone** [comment]
Mostly manually. I will try to split it

**Comment by windelbouwman** [comment]
If you can split it somehow, this would be good, otherwise no worries, I will look into it, but it will take me some time to view it all.

**Comment by windelbouwman** [comment]
Super! Nice job!

**Comment by youknowone** [comment]
Oh, it is merged without spliting, even more great :D

**Pull request merged**
