### PR TITLE
Update platform from CPython 3.11.5

### PR DESCRIPTION
**Pull request by youknowone**
part of #4564

ref #5050

### CODE REVIEW

**Comment by d3lm** [comment]
Yay! 🙏

**Comment by fanninpm** [comment]
Does `Lib/test/test_platform.py` need an update too?

**Comment by youknowone** [comment]
@fanninpm Thank you!

**Comment by youknowone** [comment]
```
======================================================================
ERROR: test_architecture_via_symlink (test.test_platform.PlatformTest.test_architecture_via_symlink)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\RustPython\RustPython\pylib\Lib\test\test_platform.py", line 84, in test_architecture_via_symlink
    with support.PythonSymlink() as py:
  File "D:\a\RustPython\RustPython\pylib\Lib\test\support\__init__.py", line 1478, in __init__
    self._platform_specific()
  File "D:\a\RustPython\RustPython\pylib\Lib\test\support\__init__.py", line 1490, in _platform_specific
    dll = _winapi.GetModuleFileName(sys.dllhandle)
AttributeError: module 'sys' has no attribute 'dllhandle'
```

**Pull request merged**
