### PR TITLE
Fix Windows CI

### PR DESCRIPTION
**Pull request by derlih**
Attempt to address #5166

### CODE REVIEW

**Comment by youknowone** [comment]
Thank you so much! miri failing doesn't like related.

**Comment by derlih** [comment]
Let me polish it a bit. =)

**Comment by derlih** [comment]
@youknowone  can you clean up the [build cache](https://github.com/RustPython/RustPython/actions/caches) from this job?
It doesn't contain SSL build and cargo-vcpkg, but I can't invalidate it in an easy way.

**Comment by youknowone** [comment]
Triggered running again after deleting cache

**Comment by youknowone** [comment]
The result looks fine

**Comment by derlih** [comment]
But not perfect =)
It uses cached `cargo-vcpkg` but still compiles OpenSSL from sources.
It takes extra 5 minutes of the Windows build. I though `vcpkg` will use cached OpenSSL build.

**Review by youknowone — APPROVED** [review]
Thank you so much. Working CI is always better than broken one, so let's merge it first.

How about additonally adding vcpkg directory to `actions/cache`? would it fix it?

**Comment by derlih** [comment]
The problem is that `cargo-vcpkg`, `vcpkg` itself and `OpenSSL` build are cached by rust-cache action. But I guess after the cache restoration the timestamps from files don't match and that's why it needs to build `OpenSSL` on each build.

**Comment by youknowone** [comment]
Thank you for explanation

**Pull request merged**
